// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: diary.proto

package diary_client

import (
	"context"

	"github.com/me2/diary/rpc/diary"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserDiaryRequest      = diary.CreateUserDiaryRequest
	CreateUserDiaryResponse     = diary.CreateUserDiaryResponse
	DiaryInfo                   = diary.DiaryInfo
	GenerateAvatarDiaryRequest  = diary.GenerateAvatarDiaryRequest
	GenerateAvatarDiaryResponse = diary.GenerateAvatarDiaryResponse
	GetAvatarDiaryListRequest   = diary.GetAvatarDiaryListRequest
	GetAvatarDiaryListResponse  = diary.GetAvatarDiaryListResponse
	GetDiaryStatsRequest        = diary.GetDiaryStatsRequest
	GetDiaryStatsResponse       = diary.GetDiaryStatsResponse
	GetUserDiaryListRequest     = diary.GetUserDiaryListRequest
	GetUserDiaryListResponse    = diary.GetUserDiaryListResponse

	Diary interface {
		// 生成分身日记（由 Scheduler 调用）
		GenerateAvatarDiary(ctx context.Context, in *GenerateAvatarDiaryRequest, opts ...grpc.CallOption) (*GenerateAvatarDiaryResponse, error)
		// 获取分身日记列表
		GetAvatarDiaryList(ctx context.Context, in *GetAvatarDiaryListRequest, opts ...grpc.CallOption) (*GetAvatarDiaryListResponse, error)
		// 创建用户日记
		CreateUserDiary(ctx context.Context, in *CreateUserDiaryRequest, opts ...grpc.CallOption) (*CreateUserDiaryResponse, error)
		// 获取用户日记列表
		GetUserDiaryList(ctx context.Context, in *GetUserDiaryListRequest, opts ...grpc.CallOption) (*GetUserDiaryListResponse, error)
		// 获取日记统计
		GetDiaryStats(ctx context.Context, in *GetDiaryStatsRequest, opts ...grpc.CallOption) (*GetDiaryStatsResponse, error)
	}

	defaultDiary struct {
		cli zrpc.Client
	}
)

func NewDiary(cli zrpc.Client) Diary {
	return &defaultDiary{
		cli: cli,
	}
}

// 生成分身日记（由 Scheduler 调用）
func (m *defaultDiary) GenerateAvatarDiary(ctx context.Context, in *GenerateAvatarDiaryRequest, opts ...grpc.CallOption) (*GenerateAvatarDiaryResponse, error) {
	client := diary.NewDiaryClient(m.cli.Conn())
	return client.GenerateAvatarDiary(ctx, in, opts...)
}

// 获取分身日记列表
func (m *defaultDiary) GetAvatarDiaryList(ctx context.Context, in *GetAvatarDiaryListRequest, opts ...grpc.CallOption) (*GetAvatarDiaryListResponse, error) {
	client := diary.NewDiaryClient(m.cli.Conn())
	return client.GetAvatarDiaryList(ctx, in, opts...)
}

// 创建用户日记
func (m *defaultDiary) CreateUserDiary(ctx context.Context, in *CreateUserDiaryRequest, opts ...grpc.CallOption) (*CreateUserDiaryResponse, error) {
	client := diary.NewDiaryClient(m.cli.Conn())
	return client.CreateUserDiary(ctx, in, opts...)
}

// 获取用户日记列表
func (m *defaultDiary) GetUserDiaryList(ctx context.Context, in *GetUserDiaryListRequest, opts ...grpc.CallOption) (*GetUserDiaryListResponse, error) {
	client := diary.NewDiaryClient(m.cli.Conn())
	return client.GetUserDiaryList(ctx, in, opts...)
}

// 获取日记统计
func (m *defaultDiary) GetDiaryStats(ctx context.Context, in *GetDiaryStatsRequest, opts ...grpc.CallOption) (*GetDiaryStatsResponse, error) {
	client := diary.NewDiaryClient(m.cli.Conn())
	return client.GetDiaryStats(ctx, in, opts...)
}
