// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: avatar.proto

package avatar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Avatar_CreateAvatar_FullMethodName         = "/avatar.Avatar/CreateAvatar"
	Avatar_GetMyAvatar_FullMethodName          = "/avatar.Avatar/GetMyAvatar"
	Avatar_GetAvatarInfo_FullMethodName        = "/avatar.Avatar/GetAvatarInfo"
	Avatar_UpdateAvatarProfile_FullMethodName  = "/avatar.Avatar/UpdateAvatarProfile"
	Avatar_GetAvatarUploadToken_FullMethodName = "/avatar.Avatar/GetAvatarUploadToken"
	Avatar_CompleteAvatarUpload_FullMethodName = "/avatar.Avatar/CompleteAvatarUpload"
	Avatar_UpdatePersonality_FullMethodName    = "/avatar.Avatar/UpdatePersonality"
)

// AvatarClient is the client API for Avatar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Avatar 服务
type AvatarClient interface {
	// 创建分身
	CreateAvatar(ctx context.Context, in *CreateAvatarRequest, opts ...grpc.CallOption) (*CreateAvatarResponse, error)
	// 获取当前用户的分身
	GetMyAvatar(ctx context.Context, in *GetMyAvatarRequest, opts ...grpc.CallOption) (*GetMyAvatarResponse, error)
	// 获取分身详情
	GetAvatarInfo(ctx context.Context, in *GetAvatarInfoRequest, opts ...grpc.CallOption) (*GetAvatarInfoResponse, error)
	// 更新分身资料
	UpdateAvatarProfile(ctx context.Context, in *UpdateAvatarProfileRequest, opts ...grpc.CallOption) (*UpdateAvatarProfileResponse, error)
	// 获取头像上传凭证
	GetAvatarUploadToken(ctx context.Context, in *GetAvatarUploadTokenRequest, opts ...grpc.CallOption) (*GetAvatarUploadTokenResponse, error)
	// 完成头像上传
	CompleteAvatarUpload(ctx context.Context, in *CompleteAvatarUploadRequest, opts ...grpc.CallOption) (*CompleteAvatarUploadResponse, error)
	// 更新人格特征（由事件触发）
	UpdatePersonality(ctx context.Context, in *UpdatePersonalityRequest, opts ...grpc.CallOption) (*UpdatePersonalityResponse, error)
}

type avatarClient struct {
	cc grpc.ClientConnInterface
}

func NewAvatarClient(cc grpc.ClientConnInterface) AvatarClient {
	return &avatarClient{cc}
}

func (c *avatarClient) CreateAvatar(ctx context.Context, in *CreateAvatarRequest, opts ...grpc.CallOption) (*CreateAvatarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAvatarResponse)
	err := c.cc.Invoke(ctx, Avatar_CreateAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avatarClient) GetMyAvatar(ctx context.Context, in *GetMyAvatarRequest, opts ...grpc.CallOption) (*GetMyAvatarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyAvatarResponse)
	err := c.cc.Invoke(ctx, Avatar_GetMyAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avatarClient) GetAvatarInfo(ctx context.Context, in *GetAvatarInfoRequest, opts ...grpc.CallOption) (*GetAvatarInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvatarInfoResponse)
	err := c.cc.Invoke(ctx, Avatar_GetAvatarInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avatarClient) UpdateAvatarProfile(ctx context.Context, in *UpdateAvatarProfileRequest, opts ...grpc.CallOption) (*UpdateAvatarProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAvatarProfileResponse)
	err := c.cc.Invoke(ctx, Avatar_UpdateAvatarProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avatarClient) GetAvatarUploadToken(ctx context.Context, in *GetAvatarUploadTokenRequest, opts ...grpc.CallOption) (*GetAvatarUploadTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvatarUploadTokenResponse)
	err := c.cc.Invoke(ctx, Avatar_GetAvatarUploadToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avatarClient) CompleteAvatarUpload(ctx context.Context, in *CompleteAvatarUploadRequest, opts ...grpc.CallOption) (*CompleteAvatarUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteAvatarUploadResponse)
	err := c.cc.Invoke(ctx, Avatar_CompleteAvatarUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avatarClient) UpdatePersonality(ctx context.Context, in *UpdatePersonalityRequest, opts ...grpc.CallOption) (*UpdatePersonalityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePersonalityResponse)
	err := c.cc.Invoke(ctx, Avatar_UpdatePersonality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvatarServer is the server API for Avatar service.
// All implementations must embed UnimplementedAvatarServer
// for forward compatibility.
//
// Avatar 服务
type AvatarServer interface {
	// 创建分身
	CreateAvatar(context.Context, *CreateAvatarRequest) (*CreateAvatarResponse, error)
	// 获取当前用户的分身
	GetMyAvatar(context.Context, *GetMyAvatarRequest) (*GetMyAvatarResponse, error)
	// 获取分身详情
	GetAvatarInfo(context.Context, *GetAvatarInfoRequest) (*GetAvatarInfoResponse, error)
	// 更新分身资料
	UpdateAvatarProfile(context.Context, *UpdateAvatarProfileRequest) (*UpdateAvatarProfileResponse, error)
	// 获取头像上传凭证
	GetAvatarUploadToken(context.Context, *GetAvatarUploadTokenRequest) (*GetAvatarUploadTokenResponse, error)
	// 完成头像上传
	CompleteAvatarUpload(context.Context, *CompleteAvatarUploadRequest) (*CompleteAvatarUploadResponse, error)
	// 更新人格特征（由事件触发）
	UpdatePersonality(context.Context, *UpdatePersonalityRequest) (*UpdatePersonalityResponse, error)
	mustEmbedUnimplementedAvatarServer()
}

// UnimplementedAvatarServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAvatarServer struct{}

func (UnimplementedAvatarServer) CreateAvatar(context.Context, *CreateAvatarRequest) (*CreateAvatarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAvatar not implemented")
}
func (UnimplementedAvatarServer) GetMyAvatar(context.Context, *GetMyAvatarRequest) (*GetMyAvatarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyAvatar not implemented")
}
func (UnimplementedAvatarServer) GetAvatarInfo(context.Context, *GetAvatarInfoRequest) (*GetAvatarInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvatarInfo not implemented")
}
func (UnimplementedAvatarServer) UpdateAvatarProfile(context.Context, *UpdateAvatarProfileRequest) (*UpdateAvatarProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAvatarProfile not implemented")
}
func (UnimplementedAvatarServer) GetAvatarUploadToken(context.Context, *GetAvatarUploadTokenRequest) (*GetAvatarUploadTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvatarUploadToken not implemented")
}
func (UnimplementedAvatarServer) CompleteAvatarUpload(context.Context, *CompleteAvatarUploadRequest) (*CompleteAvatarUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteAvatarUpload not implemented")
}
func (UnimplementedAvatarServer) UpdatePersonality(context.Context, *UpdatePersonalityRequest) (*UpdatePersonalityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePersonality not implemented")
}
func (UnimplementedAvatarServer) mustEmbedUnimplementedAvatarServer() {}
func (UnimplementedAvatarServer) testEmbeddedByValue()                {}

// UnsafeAvatarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvatarServer will
// result in compilation errors.
type UnsafeAvatarServer interface {
	mustEmbedUnimplementedAvatarServer()
}

func RegisterAvatarServer(s grpc.ServiceRegistrar, srv AvatarServer) {
	// If the following call pancis, it indicates UnimplementedAvatarServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Avatar_ServiceDesc, srv)
}

func _Avatar_CreateAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvatarServer).CreateAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avatar_CreateAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvatarServer).CreateAvatar(ctx, req.(*CreateAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avatar_GetMyAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvatarServer).GetMyAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avatar_GetMyAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvatarServer).GetMyAvatar(ctx, req.(*GetMyAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avatar_GetAvatarInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvatarInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvatarServer).GetAvatarInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avatar_GetAvatarInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvatarServer).GetAvatarInfo(ctx, req.(*GetAvatarInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avatar_UpdateAvatarProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAvatarProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvatarServer).UpdateAvatarProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avatar_UpdateAvatarProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvatarServer).UpdateAvatarProfile(ctx, req.(*UpdateAvatarProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avatar_GetAvatarUploadToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvatarUploadTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvatarServer).GetAvatarUploadToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avatar_GetAvatarUploadToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvatarServer).GetAvatarUploadToken(ctx, req.(*GetAvatarUploadTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avatar_CompleteAvatarUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAvatarUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvatarServer).CompleteAvatarUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avatar_CompleteAvatarUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvatarServer).CompleteAvatarUpload(ctx, req.(*CompleteAvatarUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avatar_UpdatePersonality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePersonalityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvatarServer).UpdatePersonality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avatar_UpdatePersonality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvatarServer).UpdatePersonality(ctx, req.(*UpdatePersonalityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Avatar_ServiceDesc is the grpc.ServiceDesc for Avatar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Avatar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avatar.Avatar",
	HandlerType: (*AvatarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAvatar",
			Handler:    _Avatar_CreateAvatar_Handler,
		},
		{
			MethodName: "GetMyAvatar",
			Handler:    _Avatar_GetMyAvatar_Handler,
		},
		{
			MethodName: "GetAvatarInfo",
			Handler:    _Avatar_GetAvatarInfo_Handler,
		},
		{
			MethodName: "UpdateAvatarProfile",
			Handler:    _Avatar_UpdateAvatarProfile_Handler,
		},
		{
			MethodName: "GetAvatarUploadToken",
			Handler:    _Avatar_GetAvatarUploadToken_Handler,
		},
		{
			MethodName: "CompleteAvatarUpload",
			Handler:    _Avatar_CompleteAvatarUpload_Handler,
		},
		{
			MethodName: "UpdatePersonality",
			Handler:    _Avatar_UpdatePersonality_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avatar.proto",
}
