// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: action.proto

package action

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Action_ScheduleAction_FullMethodName        = "/action.Action/ScheduleAction"
	Action_CalculateActionIntent_FullMethodName = "/action.Action/CalculateActionIntent"
	Action_GetActionHistory_FullMethodName      = "/action.Action/GetActionHistory"
	Action_GetLastAction_FullMethodName         = "/action.Action/GetLastAction"
)

// ActionClient is the client API for Action service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Action Service - 行动逻辑服务
type ActionClient interface {
	// 调度行动 - 由定时任务调用，触发分身行动
	ScheduleAction(ctx context.Context, in *ScheduleActionRequest, opts ...grpc.CallOption) (*ScheduleActionResponse, error)
	// 计算行动意图 - 计算 6 种行为的得分
	CalculateActionIntent(ctx context.Context, in *CalculateActionIntentRequest, opts ...grpc.CallOption) (*CalculateActionIntentResponse, error)
	// 获取行动历史
	GetActionHistory(ctx context.Context, in *GetActionHistoryRequest, opts ...grpc.CallOption) (*GetActionHistoryResponse, error)
	// 获取最近一次行动
	GetLastAction(ctx context.Context, in *GetLastActionRequest, opts ...grpc.CallOption) (*GetLastActionResponse, error)
}

type actionClient struct {
	cc grpc.ClientConnInterface
}

func NewActionClient(cc grpc.ClientConnInterface) ActionClient {
	return &actionClient{cc}
}

func (c *actionClient) ScheduleAction(ctx context.Context, in *ScheduleActionRequest, opts ...grpc.CallOption) (*ScheduleActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleActionResponse)
	err := c.cc.Invoke(ctx, Action_ScheduleAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) CalculateActionIntent(ctx context.Context, in *CalculateActionIntentRequest, opts ...grpc.CallOption) (*CalculateActionIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateActionIntentResponse)
	err := c.cc.Invoke(ctx, Action_CalculateActionIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) GetActionHistory(ctx context.Context, in *GetActionHistoryRequest, opts ...grpc.CallOption) (*GetActionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActionHistoryResponse)
	err := c.cc.Invoke(ctx, Action_GetActionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionClient) GetLastAction(ctx context.Context, in *GetLastActionRequest, opts ...grpc.CallOption) (*GetLastActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastActionResponse)
	err := c.cc.Invoke(ctx, Action_GetLastAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActionServer is the server API for Action service.
// All implementations must embed UnimplementedActionServer
// for forward compatibility.
//
// Action Service - 行动逻辑服务
type ActionServer interface {
	// 调度行动 - 由定时任务调用，触发分身行动
	ScheduleAction(context.Context, *ScheduleActionRequest) (*ScheduleActionResponse, error)
	// 计算行动意图 - 计算 6 种行为的得分
	CalculateActionIntent(context.Context, *CalculateActionIntentRequest) (*CalculateActionIntentResponse, error)
	// 获取行动历史
	GetActionHistory(context.Context, *GetActionHistoryRequest) (*GetActionHistoryResponse, error)
	// 获取最近一次行动
	GetLastAction(context.Context, *GetLastActionRequest) (*GetLastActionResponse, error)
	mustEmbedUnimplementedActionServer()
}

// UnimplementedActionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActionServer struct{}

func (UnimplementedActionServer) ScheduleAction(context.Context, *ScheduleActionRequest) (*ScheduleActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleAction not implemented")
}
func (UnimplementedActionServer) CalculateActionIntent(context.Context, *CalculateActionIntentRequest) (*CalculateActionIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateActionIntent not implemented")
}
func (UnimplementedActionServer) GetActionHistory(context.Context, *GetActionHistoryRequest) (*GetActionHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActionHistory not implemented")
}
func (UnimplementedActionServer) GetLastAction(context.Context, *GetLastActionRequest) (*GetLastActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastAction not implemented")
}
func (UnimplementedActionServer) mustEmbedUnimplementedActionServer() {}
func (UnimplementedActionServer) testEmbeddedByValue()                {}

// UnsafeActionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActionServer will
// result in compilation errors.
type UnsafeActionServer interface {
	mustEmbedUnimplementedActionServer()
}

func RegisterActionServer(s grpc.ServiceRegistrar, srv ActionServer) {
	// If the following call pancis, it indicates UnimplementedActionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Action_ServiceDesc, srv)
}

func _Action_ScheduleAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).ScheduleAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Action_ScheduleAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).ScheduleAction(ctx, req.(*ScheduleActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_CalculateActionIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateActionIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).CalculateActionIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Action_CalculateActionIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).CalculateActionIntent(ctx, req.(*CalculateActionIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_GetActionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).GetActionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Action_GetActionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).GetActionHistory(ctx, req.(*GetActionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Action_GetLastAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).GetLastAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Action_GetLastAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).GetLastAction(ctx, req.(*GetLastActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Action_ServiceDesc is the grpc.ServiceDesc for Action service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Action_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "action.Action",
	HandlerType: (*ActionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleAction",
			Handler:    _Action_ScheduleAction_Handler,
		},
		{
			MethodName: "CalculateActionIntent",
			Handler:    _Action_CalculateActionIntent_Handler,
		},
		{
			MethodName: "GetActionHistory",
			Handler:    _Action_GetActionHistory_Handler,
		},
		{
			MethodName: "GetLastAction",
			Handler:    _Action_GetLastAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "action.proto",
}
