// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: event.proto

package server

import (
	"context"

	"github.com/me2/event/rpc/event"
	"github.com/me2/event/rpc/internal/logic"
	"github.com/me2/event/rpc/internal/svc"
)

type EventServer struct {
	svcCtx *svc.ServiceContext
	event.UnimplementedEventServer
}

func NewEventServer(svcCtx *svc.ServiceContext) *EventServer {
	return &EventServer{
		svcCtx: svcCtx,
	}
}

// 生成事件
func (s *EventServer) GenerateEvent(ctx context.Context, in *event.GenerateEventRequest) (*event.GenerateEventResponse, error) {
	l := logic.NewGenerateEventLogic(ctx, s.svcCtx)
	return l.GenerateEvent(in)
}

// 获取事件时间线
func (s *EventServer) GetEventTimeline(ctx context.Context, in *event.GetEventTimelineRequest) (*event.GetEventTimelineResponse, error) {
	l := logic.NewGetEventTimelineLogic(ctx, s.svcCtx)
	return l.GetEventTimeline(in)
}

// 获取事件详情
func (s *EventServer) GetEventDetail(ctx context.Context, in *event.GetEventDetailRequest) (*event.GetEventDetailResponse, error) {
	l := logic.NewGetEventDetailLogic(ctx, s.svcCtx)
	return l.GetEventDetail(in)
}

// 获取模板列表（后续可用于管理后台）
func (s *EventServer) GetTemplates(ctx context.Context, in *event.GetTemplatesRequest) (*event.GetTemplatesResponse, error) {
	l := logic.NewGetTemplatesLogic(ctx, s.svcCtx)
	return l.GetTemplates(in)
}
