// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: sms.proto

package server

import (
	"context"

	"github.com/me2/sms/rpc/internal/logic"
	"github.com/me2/sms/rpc/internal/svc"
	"github.com/me2/sms/rpc/sms"
)

type SmsServer struct {
	svcCtx *svc.ServiceContext
	sms.UnimplementedSmsServer
}

func NewSmsServer(svcCtx *svc.ServiceContext) *SmsServer {
	return &SmsServer{
		svcCtx: svcCtx,
	}
}

// 发送验证码
func (s *SmsServer) SendCode(ctx context.Context, in *sms.SendCodeRequest) (*sms.SendCodeResponse, error) {
	l := logic.NewSendCodeLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

// 验证验证码
func (s *SmsServer) VerifyCode(ctx context.Context, in *sms.VerifyCodeRequest) (*sms.VerifyCodeResponse, error) {
	l := logic.NewVerifyCodeLogic(ctx, s.svcCtx)
	return l.VerifyCode(in)
}
