// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: action.proto

package action_client

import (
	"context"

	"github.com/me2/action/rpc/action"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionIntent                  = action.ActionIntent
	ActionLog                     = action.ActionLog
	CalculateActionIntentRequest  = action.CalculateActionIntentRequest
	CalculateActionIntentResponse = action.CalculateActionIntentResponse
	GetActionHistoryRequest       = action.GetActionHistoryRequest
	GetActionHistoryResponse      = action.GetActionHistoryResponse
	GetLastActionRequest          = action.GetLastActionRequest
	GetLastActionResponse         = action.GetLastActionResponse
	ScheduleActionRequest         = action.ScheduleActionRequest
	ScheduleActionResponse        = action.ScheduleActionResponse

	Action interface {
		// 调度行动 - 由定时任务调用，触发分身行动
		ScheduleAction(ctx context.Context, in *ScheduleActionRequest, opts ...grpc.CallOption) (*ScheduleActionResponse, error)
		// 计算行动意图 - 计算 6 种行为的得分
		CalculateActionIntent(ctx context.Context, in *CalculateActionIntentRequest, opts ...grpc.CallOption) (*CalculateActionIntentResponse, error)
		// 获取行动历史
		GetActionHistory(ctx context.Context, in *GetActionHistoryRequest, opts ...grpc.CallOption) (*GetActionHistoryResponse, error)
		// 获取最近一次行动
		GetLastAction(ctx context.Context, in *GetLastActionRequest, opts ...grpc.CallOption) (*GetLastActionResponse, error)
	}

	defaultAction struct {
		cli zrpc.Client
	}
)

func NewAction(cli zrpc.Client) Action {
	return &defaultAction{
		cli: cli,
	}
}

// 调度行动 - 由定时任务调用，触发分身行动
func (m *defaultAction) ScheduleAction(ctx context.Context, in *ScheduleActionRequest, opts ...grpc.CallOption) (*ScheduleActionResponse, error) {
	client := action.NewActionClient(m.cli.Conn())
	return client.ScheduleAction(ctx, in, opts...)
}

// 计算行动意图 - 计算 6 种行为的得分
func (m *defaultAction) CalculateActionIntent(ctx context.Context, in *CalculateActionIntentRequest, opts ...grpc.CallOption) (*CalculateActionIntentResponse, error) {
	client := action.NewActionClient(m.cli.Conn())
	return client.CalculateActionIntent(ctx, in, opts...)
}

// 获取行动历史
func (m *defaultAction) GetActionHistory(ctx context.Context, in *GetActionHistoryRequest, opts ...grpc.CallOption) (*GetActionHistoryResponse, error) {
	client := action.NewActionClient(m.cli.Conn())
	return client.GetActionHistory(ctx, in, opts...)
}

// 获取最近一次行动
func (m *defaultAction) GetLastAction(ctx context.Context, in *GetLastActionRequest, opts ...grpc.CallOption) (*GetLastActionResponse, error) {
	client := action.NewActionClient(m.cli.Conn())
	return client.GetLastAction(ctx, in, opts...)
}
