// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: avatar.proto

package server

import (
	"context"

	"github.com/me2/avatar/rpc/avatar"
	"github.com/me2/avatar/rpc/internal/logic"
	"github.com/me2/avatar/rpc/internal/svc"
)

type AvatarServer struct {
	svcCtx *svc.ServiceContext
	avatar.UnimplementedAvatarServer
}

func NewAvatarServer(svcCtx *svc.ServiceContext) *AvatarServer {
	return &AvatarServer{
		svcCtx: svcCtx,
	}
}

// 创建分身
func (s *AvatarServer) CreateAvatar(ctx context.Context, in *avatar.CreateAvatarRequest) (*avatar.CreateAvatarResponse, error) {
	l := logic.NewCreateAvatarLogic(ctx, s.svcCtx)
	return l.CreateAvatar(in)
}

// 获取当前用户的分身
func (s *AvatarServer) GetMyAvatar(ctx context.Context, in *avatar.GetMyAvatarRequest) (*avatar.GetMyAvatarResponse, error) {
	l := logic.NewGetMyAvatarLogic(ctx, s.svcCtx)
	return l.GetMyAvatar(in)
}

// 获取分身详情
func (s *AvatarServer) GetAvatarInfo(ctx context.Context, in *avatar.GetAvatarInfoRequest) (*avatar.GetAvatarInfoResponse, error) {
	l := logic.NewGetAvatarInfoLogic(ctx, s.svcCtx)
	return l.GetAvatarInfo(in)
}

// 更新分身资料
func (s *AvatarServer) UpdateAvatarProfile(ctx context.Context, in *avatar.UpdateAvatarProfileRequest) (*avatar.UpdateAvatarProfileResponse, error) {
	l := logic.NewUpdateAvatarProfileLogic(ctx, s.svcCtx)
	return l.UpdateAvatarProfile(in)
}

// 获取头像上传凭证
func (s *AvatarServer) GetAvatarUploadToken(ctx context.Context, in *avatar.GetAvatarUploadTokenRequest) (*avatar.GetAvatarUploadTokenResponse, error) {
	l := logic.NewGetAvatarUploadTokenLogic(ctx, s.svcCtx)
	return l.GetAvatarUploadToken(in)
}

// 完成头像上传
func (s *AvatarServer) CompleteAvatarUpload(ctx context.Context, in *avatar.CompleteAvatarUploadRequest) (*avatar.CompleteAvatarUploadResponse, error) {
	l := logic.NewCompleteAvatarUploadLogic(ctx, s.svcCtx)
	return l.CompleteAvatarUpload(in)
}
