// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: note.proto

package noteservice

import (
	"context"

	"github.com/me2/note/rpc/note"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateNoteRequest        = note.CreateNoteRequest
	CreateNoteResponse       = note.CreateNoteResponse
	DailyExpense             = note.DailyExpense
	DeleteNoteRequest        = note.DeleteNoteRequest
	DeleteNoteResponse       = note.DeleteNoteResponse
	EmotionData              = note.EmotionData
	ExpenseInfo              = note.ExpenseInfo
	GetExpenseStatsRequest   = note.GetExpenseStatsRequest
	GetExpenseStatsResponse  = note.GetExpenseStatsResponse
	GetExpensesRequest       = note.GetExpensesRequest
	GetExpensesResponse      = note.GetExpensesResponse
	GetNoteDetailRequest     = note.GetNoteDetailRequest
	GetNoteDetailResponse    = note.GetNoteDetailResponse
	GetNotesRequest          = note.GetNotesRequest
	GetNotesResponse         = note.GetNotesResponse
	GetTodosRequest          = note.GetTodosRequest
	GetTodosResponse         = note.GetTodosResponse
	NoteInfo                 = note.NoteInfo
	SearchNotesRequest       = note.SearchNotesRequest
	SearchNotesResponse      = note.SearchNotesResponse
	TodoInfo                 = note.TodoInfo
	UpdateNoteRequest        = note.UpdateNoteRequest
	UpdateNoteResponse       = note.UpdateNoteResponse
	UpdateTodoStatusRequest  = note.UpdateTodoStatusRequest
	UpdateTodoStatusResponse = note.UpdateTodoStatusResponse

	NoteService interface {
		// 创建笔记
		CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
		// 获取笔记列表
		GetNotes(ctx context.Context, in *GetNotesRequest, opts ...grpc.CallOption) (*GetNotesResponse, error)
		// 获取笔记详情
		GetNoteDetail(ctx context.Context, in *GetNoteDetailRequest, opts ...grpc.CallOption) (*GetNoteDetailResponse, error)
		// 更新笔记
		UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error)
		// 删除笔记
		DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
		// 搜索笔记（用于对话集成）
		SearchNotes(ctx context.Context, in *SearchNotesRequest, opts ...grpc.CallOption) (*SearchNotesResponse, error)
		// 获取 TODO 列表
		GetTodos(ctx context.Context, in *GetTodosRequest, opts ...grpc.CallOption) (*GetTodosResponse, error)
		// 更新 TODO 状态
		UpdateTodoStatus(ctx context.Context, in *UpdateTodoStatusRequest, opts ...grpc.CallOption) (*UpdateTodoStatusResponse, error)
		// 获取记账列表
		GetExpenses(ctx context.Context, in *GetExpensesRequest, opts ...grpc.CallOption) (*GetExpensesResponse, error)
		// 获取记账统计
		GetExpenseStats(ctx context.Context, in *GetExpenseStatsRequest, opts ...grpc.CallOption) (*GetExpenseStatsResponse, error)
	}

	defaultNoteService struct {
		cli zrpc.Client
	}
)

func NewNoteService(cli zrpc.Client) NoteService {
	return &defaultNoteService{
		cli: cli,
	}
}

// 创建笔记
func (m *defaultNoteService) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.CreateNote(ctx, in, opts...)
}

// 获取笔记列表
func (m *defaultNoteService) GetNotes(ctx context.Context, in *GetNotesRequest, opts ...grpc.CallOption) (*GetNotesResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.GetNotes(ctx, in, opts...)
}

// 获取笔记详情
func (m *defaultNoteService) GetNoteDetail(ctx context.Context, in *GetNoteDetailRequest, opts ...grpc.CallOption) (*GetNoteDetailResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.GetNoteDetail(ctx, in, opts...)
}

// 更新笔记
func (m *defaultNoteService) UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.UpdateNote(ctx, in, opts...)
}

// 删除笔记
func (m *defaultNoteService) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.DeleteNote(ctx, in, opts...)
}

// 搜索笔记（用于对话集成）
func (m *defaultNoteService) SearchNotes(ctx context.Context, in *SearchNotesRequest, opts ...grpc.CallOption) (*SearchNotesResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.SearchNotes(ctx, in, opts...)
}

// 获取 TODO 列表
func (m *defaultNoteService) GetTodos(ctx context.Context, in *GetTodosRequest, opts ...grpc.CallOption) (*GetTodosResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.GetTodos(ctx, in, opts...)
}

// 更新 TODO 状态
func (m *defaultNoteService) UpdateTodoStatus(ctx context.Context, in *UpdateTodoStatusRequest, opts ...grpc.CallOption) (*UpdateTodoStatusResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.UpdateTodoStatus(ctx, in, opts...)
}

// 获取记账列表
func (m *defaultNoteService) GetExpenses(ctx context.Context, in *GetExpensesRequest, opts ...grpc.CallOption) (*GetExpensesResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.GetExpenses(ctx, in, opts...)
}

// 获取记账统计
func (m *defaultNoteService) GetExpenseStats(ctx context.Context, in *GetExpenseStatsRequest, opts ...grpc.CallOption) (*GetExpenseStatsResponse, error) {
	client := note.NewNoteServiceClient(m.cli.Conn())
	return client.GetExpenseStats(ctx, in, opts...)
}
