// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: scheduler.proto

package scheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scheduler_EnableAvatarSchedule_FullMethodName    = "/scheduler.Scheduler/EnableAvatarSchedule"
	Scheduler_PauseAvatarSchedule_FullMethodName     = "/scheduler.Scheduler/PauseAvatarSchedule"
	Scheduler_ResumeAvatarSchedule_FullMethodName    = "/scheduler.Scheduler/ResumeAvatarSchedule"
	Scheduler_GetAvatarScheduleStatus_FullMethodName = "/scheduler.Scheduler/GetAvatarScheduleStatus"
	Scheduler_TriggerSchedule_FullMethodName         = "/scheduler.Scheduler/TriggerSchedule"
	Scheduler_BatchGetScheduleStatus_FullMethodName  = "/scheduler.Scheduler/BatchGetScheduleStatus"
)

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 调度管理服务
type SchedulerClient interface {
	// 启用分身调度
	EnableAvatarSchedule(ctx context.Context, in *EnableAvatarScheduleRequest, opts ...grpc.CallOption) (*EnableAvatarScheduleResponse, error)
	// 暂停分身调度
	PauseAvatarSchedule(ctx context.Context, in *PauseAvatarScheduleRequest, opts ...grpc.CallOption) (*PauseAvatarScheduleResponse, error)
	// 恢复分身调度
	ResumeAvatarSchedule(ctx context.Context, in *ResumeAvatarScheduleRequest, opts ...grpc.CallOption) (*ResumeAvatarScheduleResponse, error)
	// 获取分身调度状态
	GetAvatarScheduleStatus(ctx context.Context, in *GetAvatarScheduleStatusRequest, opts ...grpc.CallOption) (*GetAvatarScheduleStatusResponse, error)
	// 手动触发一次调度
	TriggerSchedule(ctx context.Context, in *TriggerScheduleRequest, opts ...grpc.CallOption) (*TriggerScheduleResponse, error)
	// 批量获取调度状态
	BatchGetScheduleStatus(ctx context.Context, in *BatchGetScheduleStatusRequest, opts ...grpc.CallOption) (*BatchGetScheduleStatusResponse, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) EnableAvatarSchedule(ctx context.Context, in *EnableAvatarScheduleRequest, opts ...grpc.CallOption) (*EnableAvatarScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableAvatarScheduleResponse)
	err := c.cc.Invoke(ctx, Scheduler_EnableAvatarSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) PauseAvatarSchedule(ctx context.Context, in *PauseAvatarScheduleRequest, opts ...grpc.CallOption) (*PauseAvatarScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseAvatarScheduleResponse)
	err := c.cc.Invoke(ctx, Scheduler_PauseAvatarSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ResumeAvatarSchedule(ctx context.Context, in *ResumeAvatarScheduleRequest, opts ...grpc.CallOption) (*ResumeAvatarScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeAvatarScheduleResponse)
	err := c.cc.Invoke(ctx, Scheduler_ResumeAvatarSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetAvatarScheduleStatus(ctx context.Context, in *GetAvatarScheduleStatusRequest, opts ...grpc.CallOption) (*GetAvatarScheduleStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvatarScheduleStatusResponse)
	err := c.cc.Invoke(ctx, Scheduler_GetAvatarScheduleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) TriggerSchedule(ctx context.Context, in *TriggerScheduleRequest, opts ...grpc.CallOption) (*TriggerScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerScheduleResponse)
	err := c.cc.Invoke(ctx, Scheduler_TriggerSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) BatchGetScheduleStatus(ctx context.Context, in *BatchGetScheduleStatusRequest, opts ...grpc.CallOption) (*BatchGetScheduleStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetScheduleStatusResponse)
	err := c.cc.Invoke(ctx, Scheduler_BatchGetScheduleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
// All implementations must embed UnimplementedSchedulerServer
// for forward compatibility.
//
// 调度管理服务
type SchedulerServer interface {
	// 启用分身调度
	EnableAvatarSchedule(context.Context, *EnableAvatarScheduleRequest) (*EnableAvatarScheduleResponse, error)
	// 暂停分身调度
	PauseAvatarSchedule(context.Context, *PauseAvatarScheduleRequest) (*PauseAvatarScheduleResponse, error)
	// 恢复分身调度
	ResumeAvatarSchedule(context.Context, *ResumeAvatarScheduleRequest) (*ResumeAvatarScheduleResponse, error)
	// 获取分身调度状态
	GetAvatarScheduleStatus(context.Context, *GetAvatarScheduleStatusRequest) (*GetAvatarScheduleStatusResponse, error)
	// 手动触发一次调度
	TriggerSchedule(context.Context, *TriggerScheduleRequest) (*TriggerScheduleResponse, error)
	// 批量获取调度状态
	BatchGetScheduleStatus(context.Context, *BatchGetScheduleStatusRequest) (*BatchGetScheduleStatusResponse, error)
	mustEmbedUnimplementedSchedulerServer()
}

// UnimplementedSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServer struct{}

func (UnimplementedSchedulerServer) EnableAvatarSchedule(context.Context, *EnableAvatarScheduleRequest) (*EnableAvatarScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableAvatarSchedule not implemented")
}
func (UnimplementedSchedulerServer) PauseAvatarSchedule(context.Context, *PauseAvatarScheduleRequest) (*PauseAvatarScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseAvatarSchedule not implemented")
}
func (UnimplementedSchedulerServer) ResumeAvatarSchedule(context.Context, *ResumeAvatarScheduleRequest) (*ResumeAvatarScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeAvatarSchedule not implemented")
}
func (UnimplementedSchedulerServer) GetAvatarScheduleStatus(context.Context, *GetAvatarScheduleStatusRequest) (*GetAvatarScheduleStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvatarScheduleStatus not implemented")
}
func (UnimplementedSchedulerServer) TriggerSchedule(context.Context, *TriggerScheduleRequest) (*TriggerScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerSchedule not implemented")
}
func (UnimplementedSchedulerServer) BatchGetScheduleStatus(context.Context, *BatchGetScheduleStatusRequest) (*BatchGetScheduleStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetScheduleStatus not implemented")
}
func (UnimplementedSchedulerServer) mustEmbedUnimplementedSchedulerServer() {}
func (UnimplementedSchedulerServer) testEmbeddedByValue()                   {}

// UnsafeSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServer will
// result in compilation errors.
type UnsafeSchedulerServer interface {
	mustEmbedUnimplementedSchedulerServer()
}

func RegisterSchedulerServer(s grpc.ServiceRegistrar, srv SchedulerServer) {
	// If the following call pancis, it indicates UnimplementedSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scheduler_ServiceDesc, srv)
}

func _Scheduler_EnableAvatarSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableAvatarScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).EnableAvatarSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_EnableAvatarSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).EnableAvatarSchedule(ctx, req.(*EnableAvatarScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_PauseAvatarSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseAvatarScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).PauseAvatarSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_PauseAvatarSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).PauseAvatarSchedule(ctx, req.(*PauseAvatarScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ResumeAvatarSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeAvatarScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ResumeAvatarSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ResumeAvatarSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ResumeAvatarSchedule(ctx, req.(*ResumeAvatarScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetAvatarScheduleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvatarScheduleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetAvatarScheduleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_GetAvatarScheduleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetAvatarScheduleStatus(ctx, req.(*GetAvatarScheduleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_TriggerSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).TriggerSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_TriggerSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).TriggerSchedule(ctx, req.(*TriggerScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_BatchGetScheduleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetScheduleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).BatchGetScheduleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_BatchGetScheduleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).BatchGetScheduleStatus(ctx, req.(*BatchGetScheduleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduler_ServiceDesc is the grpc.ServiceDesc for Scheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnableAvatarSchedule",
			Handler:    _Scheduler_EnableAvatarSchedule_Handler,
		},
		{
			MethodName: "PauseAvatarSchedule",
			Handler:    _Scheduler_PauseAvatarSchedule_Handler,
		},
		{
			MethodName: "ResumeAvatarSchedule",
			Handler:    _Scheduler_ResumeAvatarSchedule_Handler,
		},
		{
			MethodName: "GetAvatarScheduleStatus",
			Handler:    _Scheduler_GetAvatarScheduleStatus_Handler,
		},
		{
			MethodName: "TriggerSchedule",
			Handler:    _Scheduler_TriggerSchedule_Handler,
		},
		{
			MethodName: "BatchGetScheduleStatus",
			Handler:    _Scheduler_BatchGetScheduleStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler.proto",
}
