// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: scheduler.proto

package scheduler_client

import (
	"context"

	"github.com/me2/scheduler/rpc/scheduler"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetScheduleStatusRequest   = scheduler.BatchGetScheduleStatusRequest
	BatchGetScheduleStatusResponse  = scheduler.BatchGetScheduleStatusResponse
	EnableAvatarScheduleRequest     = scheduler.EnableAvatarScheduleRequest
	EnableAvatarScheduleResponse    = scheduler.EnableAvatarScheduleResponse
	GetAvatarScheduleStatusRequest  = scheduler.GetAvatarScheduleStatusRequest
	GetAvatarScheduleStatusResponse = scheduler.GetAvatarScheduleStatusResponse
	PauseAvatarScheduleRequest      = scheduler.PauseAvatarScheduleRequest
	PauseAvatarScheduleResponse     = scheduler.PauseAvatarScheduleResponse
	ResumeAvatarScheduleRequest     = scheduler.ResumeAvatarScheduleRequest
	ResumeAvatarScheduleResponse    = scheduler.ResumeAvatarScheduleResponse
	ScheduleInfo                    = scheduler.ScheduleInfo
	TriggerScheduleRequest          = scheduler.TriggerScheduleRequest
	TriggerScheduleResponse         = scheduler.TriggerScheduleResponse

	Scheduler interface {
		// 启用分身调度
		EnableAvatarSchedule(ctx context.Context, in *EnableAvatarScheduleRequest, opts ...grpc.CallOption) (*EnableAvatarScheduleResponse, error)
		// 暂停分身调度
		PauseAvatarSchedule(ctx context.Context, in *PauseAvatarScheduleRequest, opts ...grpc.CallOption) (*PauseAvatarScheduleResponse, error)
		// 恢复分身调度
		ResumeAvatarSchedule(ctx context.Context, in *ResumeAvatarScheduleRequest, opts ...grpc.CallOption) (*ResumeAvatarScheduleResponse, error)
		// 获取分身调度状态
		GetAvatarScheduleStatus(ctx context.Context, in *GetAvatarScheduleStatusRequest, opts ...grpc.CallOption) (*GetAvatarScheduleStatusResponse, error)
		// 手动触发一次调度
		TriggerSchedule(ctx context.Context, in *TriggerScheduleRequest, opts ...grpc.CallOption) (*TriggerScheduleResponse, error)
		// 批量获取调度状态
		BatchGetScheduleStatus(ctx context.Context, in *BatchGetScheduleStatusRequest, opts ...grpc.CallOption) (*BatchGetScheduleStatusResponse, error)
	}

	defaultScheduler struct {
		cli zrpc.Client
	}
)

func NewScheduler(cli zrpc.Client) Scheduler {
	return &defaultScheduler{
		cli: cli,
	}
}

// 启用分身调度
func (m *defaultScheduler) EnableAvatarSchedule(ctx context.Context, in *EnableAvatarScheduleRequest, opts ...grpc.CallOption) (*EnableAvatarScheduleResponse, error) {
	client := scheduler.NewSchedulerClient(m.cli.Conn())
	return client.EnableAvatarSchedule(ctx, in, opts...)
}

// 暂停分身调度
func (m *defaultScheduler) PauseAvatarSchedule(ctx context.Context, in *PauseAvatarScheduleRequest, opts ...grpc.CallOption) (*PauseAvatarScheduleResponse, error) {
	client := scheduler.NewSchedulerClient(m.cli.Conn())
	return client.PauseAvatarSchedule(ctx, in, opts...)
}

// 恢复分身调度
func (m *defaultScheduler) ResumeAvatarSchedule(ctx context.Context, in *ResumeAvatarScheduleRequest, opts ...grpc.CallOption) (*ResumeAvatarScheduleResponse, error) {
	client := scheduler.NewSchedulerClient(m.cli.Conn())
	return client.ResumeAvatarSchedule(ctx, in, opts...)
}

// 获取分身调度状态
func (m *defaultScheduler) GetAvatarScheduleStatus(ctx context.Context, in *GetAvatarScheduleStatusRequest, opts ...grpc.CallOption) (*GetAvatarScheduleStatusResponse, error) {
	client := scheduler.NewSchedulerClient(m.cli.Conn())
	return client.GetAvatarScheduleStatus(ctx, in, opts...)
}

// 手动触发一次调度
func (m *defaultScheduler) TriggerSchedule(ctx context.Context, in *TriggerScheduleRequest, opts ...grpc.CallOption) (*TriggerScheduleResponse, error) {
	client := scheduler.NewSchedulerClient(m.cli.Conn())
	return client.TriggerSchedule(ctx, in, opts...)
}

// 批量获取调度状态
func (m *defaultScheduler) BatchGetScheduleStatus(ctx context.Context, in *BatchGetScheduleStatusRequest, opts ...grpc.CallOption) (*BatchGetScheduleStatusResponse, error) {
	client := scheduler.NewSchedulerClient(m.cli.Conn())
	return client.BatchGetScheduleStatus(ctx, in, opts...)
}
