// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: ai.proto

package server

import (
	"context"

	"github.com/me2/ai/rpc/ai"
	"github.com/me2/ai/rpc/internal/logic"
	"github.com/me2/ai/rpc/internal/svc"
)

type AiServer struct {
	svcCtx *svc.ServiceContext
	ai.UnimplementedAiServer
}

func NewAiServer(svcCtx *svc.ServiceContext) *AiServer {
	return &AiServer{
		svcCtx: svcCtx,
	}
}

// 对话生成（非流式）
func (s *AiServer) Chat(ctx context.Context, in *ai.ChatRequest) (*ai.ChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

// 对话生成（流式）
func (s *AiServer) ChatStream(in *ai.ChatRequest, stream ai.Ai_ChatStreamServer) error {
	l := logic.NewChatStreamLogic(stream.Context(), s.svcCtx)
	return l.ChatStream(in, stream)
}

// 文本生成（事件、日记等）
func (s *AiServer) Generate(ctx context.Context, in *ai.GenerateRequest) (*ai.GenerateResponse, error) {
	l := logic.NewGenerateLogic(ctx, s.svcCtx)
	return l.Generate(in)
}

// 情绪分析
func (s *AiServer) AnalyzeEmotion(ctx context.Context, in *ai.AnalyzeEmotionRequest) (*ai.AnalyzeEmotionResponse, error) {
	l := logic.NewAnalyzeEmotionLogic(ctx, s.svcCtx)
	return l.AnalyzeEmotion(in)
}

// 文本向量化
func (s *AiServer) Embedding(ctx context.Context, in *ai.EmbeddingRequest) (*ai.EmbeddingResponse, error) {
	l := logic.NewEmbeddingLogic(ctx, s.svcCtx)
	return l.Embedding(in)
}

// 行动意图计算（供 Action Service 调用）
func (s *AiServer) CalculateActionIntent(ctx context.Context, in *ai.ActionIntentRequest) (*ai.ActionIntentResponse, error) {
	l := logic.NewCalculateActionIntentLogic(ctx, s.svcCtx)
	return l.CalculateActionIntent(in)
}

// 获取 Prompt 模板列表
func (s *AiServer) GetPrompts(ctx context.Context, in *ai.GetPromptsRequest) (*ai.GetPromptsResponse, error) {
	l := logic.NewGetPromptsLogic(ctx, s.svcCtx)
	return l.GetPrompts(in)
}

// 获取使用统计
func (s *AiServer) GetStats(ctx context.Context, in *ai.GetStatsRequest) (*ai.GetStatsResponse, error) {
	l := logic.NewGetStatsLogic(ctx, s.svcCtx)
	return l.GetStats(in)
}

// 健康检查
func (s *AiServer) HealthCheck(ctx context.Context, in *ai.HealthCheckRequest) (*ai.HealthCheckResponse, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}
