// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: world.proto

package world_client

import (
	"context"

	"github.com/me2/world/rpc/world"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMapRequest              = world.GetMapRequest
	GetMapResponse             = world.GetMapResponse
	GetRegionRequest           = world.GetRegionRequest
	GetRegionResponse          = world.GetRegionResponse
	GetSceneRequest            = world.GetSceneRequest
	GetSceneResponse           = world.GetSceneResponse
	GetScenesForActionRequest  = world.GetScenesForActionRequest
	GetScenesForActionResponse = world.GetScenesForActionResponse
	ListMapsRequest            = world.ListMapsRequest
	ListMapsResponse           = world.ListMapsResponse
	ListRegionsInMapRequest    = world.ListRegionsInMapRequest
	ListRegionsInMapResponse   = world.ListRegionsInMapResponse
	ListScenesInRegionRequest  = world.ListScenesInRegionRequest
	ListScenesInRegionResponse = world.ListScenesInRegionResponse
	SceneFeatures              = world.SceneFeatures
	SceneRecommendation        = world.SceneRecommendation
	WorldMap                   = world.WorldMap
	WorldRegion                = world.WorldRegion
	WorldScene                 = world.WorldScene

	World interface {
		// 获取世界地图
		GetMap(ctx context.Context, in *GetMapRequest, opts ...grpc.CallOption) (*GetMapResponse, error)
		// 获取区域详情
		GetRegion(ctx context.Context, in *GetRegionRequest, opts ...grpc.CallOption) (*GetRegionResponse, error)
		// 获取场景详情
		GetScene(ctx context.Context, in *GetSceneRequest, opts ...grpc.CallOption) (*GetSceneResponse, error)
		// 列出区域内的场景
		ListScenesInRegion(ctx context.Context, in *ListScenesInRegionRequest, opts ...grpc.CallOption) (*ListScenesInRegionResponse, error)
		// 根据行为类型推荐场景
		GetScenesForAction(ctx context.Context, in *GetScenesForActionRequest, opts ...grpc.CallOption) (*GetScenesForActionResponse, error)
		// 获取所有地图列表
		ListMaps(ctx context.Context, in *ListMapsRequest, opts ...grpc.CallOption) (*ListMapsResponse, error)
		// 获取地图的所有区域
		ListRegionsInMap(ctx context.Context, in *ListRegionsInMapRequest, opts ...grpc.CallOption) (*ListRegionsInMapResponse, error)
	}

	defaultWorld struct {
		cli zrpc.Client
	}
)

func NewWorld(cli zrpc.Client) World {
	return &defaultWorld{
		cli: cli,
	}
}

// 获取世界地图
func (m *defaultWorld) GetMap(ctx context.Context, in *GetMapRequest, opts ...grpc.CallOption) (*GetMapResponse, error) {
	client := world.NewWorldClient(m.cli.Conn())
	return client.GetMap(ctx, in, opts...)
}

// 获取区域详情
func (m *defaultWorld) GetRegion(ctx context.Context, in *GetRegionRequest, opts ...grpc.CallOption) (*GetRegionResponse, error) {
	client := world.NewWorldClient(m.cli.Conn())
	return client.GetRegion(ctx, in, opts...)
}

// 获取场景详情
func (m *defaultWorld) GetScene(ctx context.Context, in *GetSceneRequest, opts ...grpc.CallOption) (*GetSceneResponse, error) {
	client := world.NewWorldClient(m.cli.Conn())
	return client.GetScene(ctx, in, opts...)
}

// 列出区域内的场景
func (m *defaultWorld) ListScenesInRegion(ctx context.Context, in *ListScenesInRegionRequest, opts ...grpc.CallOption) (*ListScenesInRegionResponse, error) {
	client := world.NewWorldClient(m.cli.Conn())
	return client.ListScenesInRegion(ctx, in, opts...)
}

// 根据行为类型推荐场景
func (m *defaultWorld) GetScenesForAction(ctx context.Context, in *GetScenesForActionRequest, opts ...grpc.CallOption) (*GetScenesForActionResponse, error) {
	client := world.NewWorldClient(m.cli.Conn())
	return client.GetScenesForAction(ctx, in, opts...)
}

// 获取所有地图列表
func (m *defaultWorld) ListMaps(ctx context.Context, in *ListMapsRequest, opts ...grpc.CallOption) (*ListMapsResponse, error) {
	client := world.NewWorldClient(m.cli.Conn())
	return client.ListMaps(ctx, in, opts...)
}

// 获取地图的所有区域
func (m *defaultWorld) ListRegionsInMap(ctx context.Context, in *ListRegionsInMapRequest, opts ...grpc.CallOption) (*ListRegionsInMapResponse, error) {
	client := world.NewWorldClient(m.cli.Conn())
	return client.ListRegionsInMap(ctx, in, opts...)
}
