// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ActionHistoryRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type ActionHistoryResponse struct {
	Total    int64               `json:"total"`
	Page     int                 `json:"page"`
	PageSize int                 `json:"page_size"`
	List     []ActionLogResponse `json:"list"`
}

type ActionIntentItem struct {
	ActionType string  `json:"action_type"`
	Score      float64 `json:"score"`
	Reason     string  `json:"reason"`
}

type ActionIntentResponse struct {
	Intents        []ActionIntentItem `json:"intents"`
	SelectedAction string             `json:"selected_action"`
}

type ActionLogResponse struct {
	Id            int64   `json:"id"`
	AvatarId      int64   `json:"avatar_id"`
	ActionType    string  `json:"action_type"`
	SceneId       int64   `json:"scene_id"`
	SceneName     string  `json:"scene_name"`
	IntentScore   float64 `json:"intent_score"`
	TriggerReason string  `json:"trigger_reason"`
	EventId       int64   `json:"event_id,omitempty"`
	CreatedAt     int64   `json:"created_at"`
}

type AvatarCompleteRequest struct {
	Key   string `json:"key"`
	Token string `json:"token"`
}

type AvatarCompleteResponse struct {
	AvatarUrl string `json:"avatar_url"`
}

type AvatarResponse struct {
	Id          int64   `json:"id"`
	UserId      int64   `json:"user_id"`
	Name        string  `json:"name"`
	AvatarUrl   string  `json:"avatar_url"`
	Warmth      float64 `json:"warmth"`
	Adventurous float64 `json:"adventurous"`
	Social      float64 `json:"social"`
	Creative    float64 `json:"creative"`
	Calm        float64 `json:"calm"`
	Energetic   float64 `json:"energetic"`
	CreatedAt   int64   `json:"created_at"`
}

type AvatarTokenResponse struct {
	Token     string `json:"token"`
	UploadUrl string `json:"upload_url"`
	Key       string `json:"key"`
	Accessid  string `json:"accessid"`
	Policy    string `json:"policy"`
	Signature string `json:"signature"`
	Dir       string `json:"dir"`
}

type AvatarUploadCompleteRequest struct {
	Key string `json:"key"`
}

type AvatarUploadCompleteResponse struct {
	AvatarUrl string `json:"avatar_url"`
}

type AvatarUploadTokenResponse struct {
	Token     string `json:"token"`
	UploadUrl string `json:"upload_url"`
	Key       string `json:"key"`
}

type CreateAvatarRequest struct {
	Name      string `json:"name"`
	AvatarUrl string `json:"avatar_url"`
}

type CreateUserDiaryRequest struct {
	Content string `json:"content"`
	Mood    string `json:"mood,optional"`
}

type DiaryListRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type DiaryListResponse struct {
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
	List     []DiaryResponse `json:"list"`
}

type DiaryResponse struct {
	Id           int64  `json:"id"`
	AvatarId     int64  `json:"avatar_id"`
	Type         string `json:"type"`
	Date         string `json:"date"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Mood         string `json:"mood"`
	ReplyContent string `json:"reply_content,optional"`
	CreatedAt    int64  `json:"created_at"`
}

type DiaryStatsResponse struct {
	TotalCount  int64 `json:"total_count"`
	AvatarCount int64 `json:"avatar_count"`
	UserCount   int64 `json:"user_count"`
}

type EventListRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type EventListResponse struct {
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
	List     []EventResponse `json:"list"`
}

type EventResponse struct {
	Id         int64  `json:"id"`
	AvatarId   int64  `json:"avatar_id"`
	EventType  string `json:"event_type"`
	EventText  string `json:"event_text"`
	ImageUrl   string `json:"image_url"`
	SceneId    int64  `json:"scene_id"`
	SceneName  string `json:"scene_name"`
	OccurredAt int64  `json:"occurred_at"`
}

type GetAvatarRequest struct {
	Id int64 `path:"id"`
}

type GetDiaryRequest struct {
	Id int64 `path:"id"`
}

type GetEventRequest struct {
	Id int64 `path:"id"`
}

type GetMapRequest struct {
	Id int64 `path:"id"`
}

type GetRegionRequest struct {
	Id int64 `path:"id"`
}

type GetSceneRequest struct {
	Id int64 `path:"id"`
}

type LoginRequest struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type LoginResponse struct {
	Token    string `json:"token"`
	UserId   int64  `json:"user_id"`
	AvatarId int64  `json:"avatar_id,omitempty"`
}

type MapListRequest struct {
	Page       int  `form:"page,default=1"`
	PageSize   int  `form:"page_size,default=20"`
	OnlyActive bool `form:"only_active,optional"`
}

type MapListResponse struct {
	Total    int64              `json:"total"`
	Page     int                `json:"page"`
	PageSize int                `json:"page_size"`
	List     []WorldMapResponse `json:"list"`
}

type RegionListRequest struct {
	MapId      int64 `form:"map_id"`
	Page       int   `form:"page,default=1"`
	PageSize   int   `form:"page_size,default=20"`
	OnlyActive bool  `form:"only_active,optional"`
}

type RegionListResponse struct {
	Total    int64                 `json:"total"`
	Page     int                   `json:"page"`
	PageSize int                   `json:"page_size"`
	List     []WorldRegionResponse `json:"list"`
}

type SceneFeaturesResponse struct {
	HasWifi      bool `json:"has_wifi"`
	HasFood      bool `json:"has_food"`
	HasSeating   bool `json:"has_seating"`
	IsIndoor     bool `json:"is_indoor"`
	IsQuiet      bool `json:"is_quiet"`
	ComfortLevel int  `json:"comfort_level"`
	SocialLevel  int  `json:"social_level"`
}

type SceneListRequest struct {
	RegionId   int64    `form:"region_id"`
	Page       int      `form:"page,default=1"`
	PageSize   int      `form:"page_size,default=20"`
	OnlyActive bool     `form:"only_active,optional"`
	Tags       []string `form:"tags,optional"`
}

type SceneListResponse struct {
	Total    int64                `json:"total"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"page_size"`
	List     []WorldSceneResponse `json:"list"`
}

type SceneRecommendationItem struct {
	Scene      WorldSceneResponse `json:"scene"`
	MatchScore float64            `json:"match_score"`
	Reason     string             `json:"reason"`
}

type SceneRecommendationRequest struct {
	ActionType string `form:"action_type"`
	MapId      int64  `form:"map_id,optional"`
	RegionId   int64  `form:"region_id,optional"`
	Limit      int    `form:"limit,default=10"`
}

type SceneRecommendationResponse struct {
	Recommendations []SceneRecommendationItem `json:"recommendations"`
}

type SendCodeRequest struct {
	Phone string `json:"phone"`
}

type SubscriptionResponse struct {
	UserId           int64 `json:"user_id"`
	SubscriptionTier int32 `json:"subscription_tier"`
	ExpiresAt        int64 `json:"expires_at,omitempty"`
	AutoRenew        bool  `json:"auto_renew"`
}

type UpdateAvatarRequest struct {
	Id        int64  `path:"id"`
	Name      string `json:"name,optional"`
	AvatarUrl string `json:"avatar_url,optional"`
}

type UpdatePersonalityRequest struct {
	Id          int64   `path:"id"`
	Warmth      float64 `json:"warmth,optional"`
	Adventurous float64 `json:"adventurous,optional"`
	Social      float64 `json:"social,optional"`
	Creative    float64 `json:"creative,optional"`
	Calm        float64 `json:"calm,optional"`
	Energetic   float64 `json:"energetic,optional"`
}

type UpdateSubscriptionRequest struct {
	UserId           int64 `json:"user_id"`
	SubscriptionTier int32 `json:"subscription_tier"`
	ExpiresAt        int64 `json:"expires_at,optional"`
}

type UpdateUserRequest struct {
	Nickname  string `json:"nickname,optional"`
	AvatarUrl string `json:"avatar_url,optional"`
}

type UpdateUserStatusRequest struct {
	UserId int64 `json:"user_id"`
	Status int32 `json:"status"`
}

type UserInfoResponse struct {
	UserId           int64  `json:"user_id"`
	Phone            string `json:"phone"`
	Nickname         string `json:"nickname"`
	AvatarUrl        string `json:"avatar_url"`
	SubscriptionTier int32  `json:"subscription_tier"`
	Status           int32  `json:"status"`
	CreatedAt        int64  `json:"created_at"`
}

type WorldMapResponse struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CoverImage  string `json:"cover_image"`
	IsActive    bool   `json:"is_active"`
	CreatedAt   int64  `json:"created_at"`
}

type WorldRegionResponse struct {
	Id          int64    `json:"id"`
	MapId       int64    `json:"map_id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	CoverImage  string   `json:"cover_image"`
	Atmosphere  string   `json:"atmosphere"`
	Tags        []string `json:"tags"`
	IsActive    bool     `json:"is_active"`
	CreatedAt   int64    `json:"created_at"`
}

type WorldSceneResponse struct {
	Id              int64                 `json:"id"`
	RegionId        int64                 `json:"region_id"`
	Name            string                `json:"name"`
	Description     string                `json:"description"`
	CoverImage      string                `json:"cover_image"`
	Atmosphere      string                `json:"atmosphere"`
	Tags            []string              `json:"tags"`
	SuitableActions []string              `json:"suitable_actions"`
	Capacity        int                   `json:"capacity"`
	IsActive        bool                  `json:"is_active"`
	Features        SceneFeaturesResponse `json:"features"`
	CreatedAt       int64                 `json:"created_at"`
}
