// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: world.proto

package server

import (
	"context"

	"github.com/me2/world/rpc/internal/logic"
	"github.com/me2/world/rpc/internal/svc"
	"github.com/me2/world/rpc/world"
)

type WorldServer struct {
	svcCtx *svc.ServiceContext
	world.UnimplementedWorldServer
}

func NewWorldServer(svcCtx *svc.ServiceContext) *WorldServer {
	return &WorldServer{
		svcCtx: svcCtx,
	}
}

// 获取世界地图
func (s *WorldServer) GetMap(ctx context.Context, in *world.GetMapRequest) (*world.GetMapResponse, error) {
	l := logic.NewGetMapLogic(ctx, s.svcCtx)
	return l.GetMap(in)
}

// 获取区域详情
func (s *WorldServer) GetRegion(ctx context.Context, in *world.GetRegionRequest) (*world.GetRegionResponse, error) {
	l := logic.NewGetRegionLogic(ctx, s.svcCtx)
	return l.GetRegion(in)
}

// 获取场景详情
func (s *WorldServer) GetScene(ctx context.Context, in *world.GetSceneRequest) (*world.GetSceneResponse, error) {
	l := logic.NewGetSceneLogic(ctx, s.svcCtx)
	return l.GetScene(in)
}

// 列出区域内的场景
func (s *WorldServer) ListScenesInRegion(ctx context.Context, in *world.ListScenesInRegionRequest) (*world.ListScenesInRegionResponse, error) {
	l := logic.NewListScenesInRegionLogic(ctx, s.svcCtx)
	return l.ListScenesInRegion(in)
}

// 根据行为类型推荐场景
func (s *WorldServer) GetScenesForAction(ctx context.Context, in *world.GetScenesForActionRequest) (*world.GetScenesForActionResponse, error) {
	l := logic.NewGetScenesForActionLogic(ctx, s.svcCtx)
	return l.GetScenesForAction(in)
}

// 获取所有地图列表
func (s *WorldServer) ListMaps(ctx context.Context, in *world.ListMapsRequest) (*world.ListMapsResponse, error) {
	l := logic.NewListMapsLogic(ctx, s.svcCtx)
	return l.ListMaps(in)
}

// 获取地图的所有区域
func (s *WorldServer) ListRegionsInMap(ctx context.Context, in *world.ListRegionsInMapRequest) (*world.ListRegionsInMapResponse, error) {
	l := logic.NewListRegionsInMapLogic(ctx, s.svcCtx)
	return l.ListRegionsInMap(in)
}
