// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package user_client

import (
	"context"

	"github.com/me2/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CompleteAvatarUploadRequest  = user.CompleteAvatarUploadRequest
	CompleteAvatarUploadResponse = user.CompleteAvatarUploadResponse
	GetAvatarUploadTokenRequest  = user.GetAvatarUploadTokenRequest
	GetAvatarUploadTokenResponse = user.GetAvatarUploadTokenResponse
	GetSubscriptionRequest       = user.GetSubscriptionRequest
	GetSubscriptionResponse      = user.GetSubscriptionResponse
	GetUserInfoRequest           = user.GetUserInfoRequest
	GetUserInfoResponse          = user.GetUserInfoResponse
	LoginOrRegisterRequest       = user.LoginOrRegisterRequest
	LoginOrRegisterResponse      = user.LoginOrRegisterResponse
	SendVerifyCodeRequest        = user.SendVerifyCodeRequest
	SendVerifyCodeResponse       = user.SendVerifyCodeResponse
	UpdateSubscriptionRequest    = user.UpdateSubscriptionRequest
	UpdateSubscriptionResponse   = user.UpdateSubscriptionResponse
	UpdateUserInfoRequest        = user.UpdateUserInfoRequest
	UpdateUserInfoResponse       = user.UpdateUserInfoResponse
	UpdateUserStatusRequest      = user.UpdateUserStatusRequest
	UpdateUserStatusResponse     = user.UpdateUserStatusResponse

	User interface {
		// 发送验证码
		SendVerifyCode(ctx context.Context, in *SendVerifyCodeRequest, opts ...grpc.CallOption) (*SendVerifyCodeResponse, error)
		// 登录或注册（手机号+验证码）
		LoginOrRegister(ctx context.Context, in *LoginOrRegisterRequest, opts ...grpc.CallOption) (*LoginOrRegisterResponse, error)
		// 获取用户信息
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		// 更新订阅状态
		UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionResponse, error)
		// 获取订阅信息
		GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error)
		// 更新用户状态
		UpdateUserStatus(ctx context.Context, in *UpdateUserStatusRequest, opts ...grpc.CallOption) (*UpdateUserStatusResponse, error)
		// 更新用户信息（昵称、头像）
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error)
		// 获取头像上传凭证
		GetAvatarUploadToken(ctx context.Context, in *GetAvatarUploadTokenRequest, opts ...grpc.CallOption) (*GetAvatarUploadTokenResponse, error)
		// 完成头像上传
		CompleteAvatarUpload(ctx context.Context, in *CompleteAvatarUploadRequest, opts ...grpc.CallOption) (*CompleteAvatarUploadResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 发送验证码
func (m *defaultUser) SendVerifyCode(ctx context.Context, in *SendVerifyCodeRequest, opts ...grpc.CallOption) (*SendVerifyCodeResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SendVerifyCode(ctx, in, opts...)
}

// 登录或注册（手机号+验证码）
func (m *defaultUser) LoginOrRegister(ctx context.Context, in *LoginOrRegisterRequest, opts ...grpc.CallOption) (*LoginOrRegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.LoginOrRegister(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// 更新订阅状态
func (m *defaultUser) UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateSubscription(ctx, in, opts...)
}

// 获取订阅信息
func (m *defaultUser) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetSubscription(ctx, in, opts...)
}

// 更新用户状态
func (m *defaultUser) UpdateUserStatus(ctx context.Context, in *UpdateUserStatusRequest, opts ...grpc.CallOption) (*UpdateUserStatusResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in, opts...)
}

// 更新用户信息（昵称、头像）
func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

// 获取头像上传凭证
func (m *defaultUser) GetAvatarUploadToken(ctx context.Context, in *GetAvatarUploadTokenRequest, opts ...grpc.CallOption) (*GetAvatarUploadTokenResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetAvatarUploadToken(ctx, in, opts...)
}

// 完成头像上传
func (m *defaultUser) CompleteAvatarUpload(ctx context.Context, in *CompleteAvatarUploadRequest, opts ...grpc.CallOption) (*CompleteAvatarUploadResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CompleteAvatarUpload(ctx, in, opts...)
}
