// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: avatar.proto

package avatar_client

import (
	"context"

	"github.com/me2/avatar/rpc/avatar"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AvatarInfo                   = avatar.AvatarInfo
	CompleteAvatarUploadRequest  = avatar.CompleteAvatarUploadRequest
	CompleteAvatarUploadResponse = avatar.CompleteAvatarUploadResponse
	CreateAvatarRequest          = avatar.CreateAvatarRequest
	CreateAvatarResponse         = avatar.CreateAvatarResponse
	GetAvatarInfoRequest         = avatar.GetAvatarInfoRequest
	GetAvatarInfoResponse        = avatar.GetAvatarInfoResponse
	GetAvatarUploadTokenRequest  = avatar.GetAvatarUploadTokenRequest
	GetAvatarUploadTokenResponse = avatar.GetAvatarUploadTokenResponse
	GetMyAvatarRequest           = avatar.GetMyAvatarRequest
	GetMyAvatarResponse          = avatar.GetMyAvatarResponse
	PersonalityInfo              = avatar.PersonalityInfo
	UpdateAvatarProfileRequest   = avatar.UpdateAvatarProfileRequest
	UpdateAvatarProfileResponse  = avatar.UpdateAvatarProfileResponse
	UpdatePersonalityRequest     = avatar.UpdatePersonalityRequest
	UpdatePersonalityResponse    = avatar.UpdatePersonalityResponse

	Avatar interface {
		// 创建分身
		CreateAvatar(ctx context.Context, in *CreateAvatarRequest, opts ...grpc.CallOption) (*CreateAvatarResponse, error)
		// 获取当前用户的分身
		GetMyAvatar(ctx context.Context, in *GetMyAvatarRequest, opts ...grpc.CallOption) (*GetMyAvatarResponse, error)
		// 获取分身详情
		GetAvatarInfo(ctx context.Context, in *GetAvatarInfoRequest, opts ...grpc.CallOption) (*GetAvatarInfoResponse, error)
		// 更新分身资料
		UpdateAvatarProfile(ctx context.Context, in *UpdateAvatarProfileRequest, opts ...grpc.CallOption) (*UpdateAvatarProfileResponse, error)
		// 获取头像上传凭证
		GetAvatarUploadToken(ctx context.Context, in *GetAvatarUploadTokenRequest, opts ...grpc.CallOption) (*GetAvatarUploadTokenResponse, error)
		// 完成头像上传
		CompleteAvatarUpload(ctx context.Context, in *CompleteAvatarUploadRequest, opts ...grpc.CallOption) (*CompleteAvatarUploadResponse, error)
		// 更新人格特征（由事件触发）
		UpdatePersonality(ctx context.Context, in *UpdatePersonalityRequest, opts ...grpc.CallOption) (*UpdatePersonalityResponse, error)
	}

	defaultAvatar struct {
		cli zrpc.Client
	}
)

func NewAvatar(cli zrpc.Client) Avatar {
	return &defaultAvatar{
		cli: cli,
	}
}

// 创建分身
func (m *defaultAvatar) CreateAvatar(ctx context.Context, in *CreateAvatarRequest, opts ...grpc.CallOption) (*CreateAvatarResponse, error) {
	client := avatar.NewAvatarClient(m.cli.Conn())
	return client.CreateAvatar(ctx, in, opts...)
}

// 获取当前用户的分身
func (m *defaultAvatar) GetMyAvatar(ctx context.Context, in *GetMyAvatarRequest, opts ...grpc.CallOption) (*GetMyAvatarResponse, error) {
	client := avatar.NewAvatarClient(m.cli.Conn())
	return client.GetMyAvatar(ctx, in, opts...)
}

// 获取分身详情
func (m *defaultAvatar) GetAvatarInfo(ctx context.Context, in *GetAvatarInfoRequest, opts ...grpc.CallOption) (*GetAvatarInfoResponse, error) {
	client := avatar.NewAvatarClient(m.cli.Conn())
	return client.GetAvatarInfo(ctx, in, opts...)
}

// 更新分身资料
func (m *defaultAvatar) UpdateAvatarProfile(ctx context.Context, in *UpdateAvatarProfileRequest, opts ...grpc.CallOption) (*UpdateAvatarProfileResponse, error) {
	client := avatar.NewAvatarClient(m.cli.Conn())
	return client.UpdateAvatarProfile(ctx, in, opts...)
}

// 获取头像上传凭证
func (m *defaultAvatar) GetAvatarUploadToken(ctx context.Context, in *GetAvatarUploadTokenRequest, opts ...grpc.CallOption) (*GetAvatarUploadTokenResponse, error) {
	client := avatar.NewAvatarClient(m.cli.Conn())
	return client.GetAvatarUploadToken(ctx, in, opts...)
}

// 完成头像上传
func (m *defaultAvatar) CompleteAvatarUpload(ctx context.Context, in *CompleteAvatarUploadRequest, opts ...grpc.CallOption) (*CompleteAvatarUploadResponse, error) {
	client := avatar.NewAvatarClient(m.cli.Conn())
	return client.CompleteAvatarUpload(ctx, in, opts...)
}

// 更新人格特征（由事件触发）
func (m *defaultAvatar) UpdatePersonality(ctx context.Context, in *UpdatePersonalityRequest, opts ...grpc.CallOption) (*UpdatePersonalityResponse, error) {
	client := avatar.NewAvatarClient(m.cli.Conn())
	return client.UpdatePersonality(ctx, in, opts...)
}
