// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Event_GenerateEvent_FullMethodName    = "/event.Event/GenerateEvent"
	Event_GetEventTimeline_FullMethodName = "/event.Event/GetEventTimeline"
	Event_GetEventDetail_FullMethodName   = "/event.Event/GetEventDetail"
	Event_GetTemplates_FullMethodName     = "/event.Event/GetTemplates"
)

// EventClient is the client API for Event service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Event Service - 事件生成服务
type EventClient interface {
	// 生成事件
	GenerateEvent(ctx context.Context, in *GenerateEventRequest, opts ...grpc.CallOption) (*GenerateEventResponse, error)
	// 获取事件时间线
	GetEventTimeline(ctx context.Context, in *GetEventTimelineRequest, opts ...grpc.CallOption) (*GetEventTimelineResponse, error)
	// 获取事件详情
	GetEventDetail(ctx context.Context, in *GetEventDetailRequest, opts ...grpc.CallOption) (*GetEventDetailResponse, error)
	// 获取模板列表（后续可用于管理后台）
	GetTemplates(ctx context.Context, in *GetTemplatesRequest, opts ...grpc.CallOption) (*GetTemplatesResponse, error)
}

type eventClient struct {
	cc grpc.ClientConnInterface
}

func NewEventClient(cc grpc.ClientConnInterface) EventClient {
	return &eventClient{cc}
}

func (c *eventClient) GenerateEvent(ctx context.Context, in *GenerateEventRequest, opts ...grpc.CallOption) (*GenerateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateEventResponse)
	err := c.cc.Invoke(ctx, Event_GenerateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetEventTimeline(ctx context.Context, in *GetEventTimelineRequest, opts ...grpc.CallOption) (*GetEventTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventTimelineResponse)
	err := c.cc.Invoke(ctx, Event_GetEventTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetEventDetail(ctx context.Context, in *GetEventDetailRequest, opts ...grpc.CallOption) (*GetEventDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventDetailResponse)
	err := c.cc.Invoke(ctx, Event_GetEventDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetTemplates(ctx context.Context, in *GetTemplatesRequest, opts ...grpc.CallOption) (*GetTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemplatesResponse)
	err := c.cc.Invoke(ctx, Event_GetTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServer is the server API for Event service.
// All implementations must embed UnimplementedEventServer
// for forward compatibility.
//
// Event Service - 事件生成服务
type EventServer interface {
	// 生成事件
	GenerateEvent(context.Context, *GenerateEventRequest) (*GenerateEventResponse, error)
	// 获取事件时间线
	GetEventTimeline(context.Context, *GetEventTimelineRequest) (*GetEventTimelineResponse, error)
	// 获取事件详情
	GetEventDetail(context.Context, *GetEventDetailRequest) (*GetEventDetailResponse, error)
	// 获取模板列表（后续可用于管理后台）
	GetTemplates(context.Context, *GetTemplatesRequest) (*GetTemplatesResponse, error)
	mustEmbedUnimplementedEventServer()
}

// UnimplementedEventServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServer struct{}

func (UnimplementedEventServer) GenerateEvent(context.Context, *GenerateEventRequest) (*GenerateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateEvent not implemented")
}
func (UnimplementedEventServer) GetEventTimeline(context.Context, *GetEventTimelineRequest) (*GetEventTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventTimeline not implemented")
}
func (UnimplementedEventServer) GetEventDetail(context.Context, *GetEventDetailRequest) (*GetEventDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventDetail not implemented")
}
func (UnimplementedEventServer) GetTemplates(context.Context, *GetTemplatesRequest) (*GetTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplates not implemented")
}
func (UnimplementedEventServer) mustEmbedUnimplementedEventServer() {}
func (UnimplementedEventServer) testEmbeddedByValue()               {}

// UnsafeEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServer will
// result in compilation errors.
type UnsafeEventServer interface {
	mustEmbedUnimplementedEventServer()
}

func RegisterEventServer(s grpc.ServiceRegistrar, srv EventServer) {
	// If the following call pancis, it indicates UnimplementedEventServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Event_ServiceDesc, srv)
}

func _Event_GenerateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GenerateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GenerateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GenerateEvent(ctx, req.(*GenerateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetEventTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetEventTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetEventTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetEventTimeline(ctx, req.(*GetEventTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetEventDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetEventDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetEventDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetEventDetail(ctx, req.(*GetEventDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Event_GetTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetTemplates(ctx, req.(*GetTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Event_ServiceDesc is the grpc.ServiceDesc for Event service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Event_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.Event",
	HandlerType: (*EventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateEvent",
			Handler:    _Event_GenerateEvent_Handler,
		},
		{
			MethodName: "GetEventTimeline",
			Handler:    _Event_GetEventTimeline_Handler,
		},
		{
			MethodName: "GetEventDetail",
			Handler:    _Event_GetEventDetail_Handler,
		},
		{
			MethodName: "GetTemplates",
			Handler:    _Event_GetTemplates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
