// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: diary.proto

package diary

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Diary_GenerateAvatarDiary_FullMethodName = "/diary.Diary/GenerateAvatarDiary"
	Diary_GetAvatarDiaryList_FullMethodName  = "/diary.Diary/GetAvatarDiaryList"
	Diary_CreateUserDiary_FullMethodName     = "/diary.Diary/CreateUserDiary"
	Diary_GetUserDiaryList_FullMethodName    = "/diary.Diary/GetUserDiaryList"
	Diary_GetDiaryStats_FullMethodName       = "/diary.Diary/GetDiaryStats"
	Diary_GetDiary_FullMethodName            = "/diary.Diary/GetDiary"
)

// DiaryClient is the client API for Diary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 日记服务
type DiaryClient interface {
	// 生成分身日记（由 Scheduler 调用）
	GenerateAvatarDiary(ctx context.Context, in *GenerateAvatarDiaryRequest, opts ...grpc.CallOption) (*GenerateAvatarDiaryResponse, error)
	// 获取分身日记列表
	GetAvatarDiaryList(ctx context.Context, in *GetAvatarDiaryListRequest, opts ...grpc.CallOption) (*GetAvatarDiaryListResponse, error)
	// 创建用户日记
	CreateUserDiary(ctx context.Context, in *CreateUserDiaryRequest, opts ...grpc.CallOption) (*CreateUserDiaryResponse, error)
	// 获取用户日记列表
	GetUserDiaryList(ctx context.Context, in *GetUserDiaryListRequest, opts ...grpc.CallOption) (*GetUserDiaryListResponse, error)
	// 获取日记统计
	GetDiaryStats(ctx context.Context, in *GetDiaryStatsRequest, opts ...grpc.CallOption) (*GetDiaryStatsResponse, error)
	// 获取日记详情
	GetDiary(ctx context.Context, in *GetDiaryRequest, opts ...grpc.CallOption) (*GetDiaryResponse, error)
}

type diaryClient struct {
	cc grpc.ClientConnInterface
}

func NewDiaryClient(cc grpc.ClientConnInterface) DiaryClient {
	return &diaryClient{cc}
}

func (c *diaryClient) GenerateAvatarDiary(ctx context.Context, in *GenerateAvatarDiaryRequest, opts ...grpc.CallOption) (*GenerateAvatarDiaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAvatarDiaryResponse)
	err := c.cc.Invoke(ctx, Diary_GenerateAvatarDiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) GetAvatarDiaryList(ctx context.Context, in *GetAvatarDiaryListRequest, opts ...grpc.CallOption) (*GetAvatarDiaryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvatarDiaryListResponse)
	err := c.cc.Invoke(ctx, Diary_GetAvatarDiaryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) CreateUserDiary(ctx context.Context, in *CreateUserDiaryRequest, opts ...grpc.CallOption) (*CreateUserDiaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserDiaryResponse)
	err := c.cc.Invoke(ctx, Diary_CreateUserDiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) GetUserDiaryList(ctx context.Context, in *GetUserDiaryListRequest, opts ...grpc.CallOption) (*GetUserDiaryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDiaryListResponse)
	err := c.cc.Invoke(ctx, Diary_GetUserDiaryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) GetDiaryStats(ctx context.Context, in *GetDiaryStatsRequest, opts ...grpc.CallOption) (*GetDiaryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiaryStatsResponse)
	err := c.cc.Invoke(ctx, Diary_GetDiaryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diaryClient) GetDiary(ctx context.Context, in *GetDiaryRequest, opts ...grpc.CallOption) (*GetDiaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiaryResponse)
	err := c.cc.Invoke(ctx, Diary_GetDiary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiaryServer is the server API for Diary service.
// All implementations must embed UnimplementedDiaryServer
// for forward compatibility.
//
// 日记服务
type DiaryServer interface {
	// 生成分身日记（由 Scheduler 调用）
	GenerateAvatarDiary(context.Context, *GenerateAvatarDiaryRequest) (*GenerateAvatarDiaryResponse, error)
	// 获取分身日记列表
	GetAvatarDiaryList(context.Context, *GetAvatarDiaryListRequest) (*GetAvatarDiaryListResponse, error)
	// 创建用户日记
	CreateUserDiary(context.Context, *CreateUserDiaryRequest) (*CreateUserDiaryResponse, error)
	// 获取用户日记列表
	GetUserDiaryList(context.Context, *GetUserDiaryListRequest) (*GetUserDiaryListResponse, error)
	// 获取日记统计
	GetDiaryStats(context.Context, *GetDiaryStatsRequest) (*GetDiaryStatsResponse, error)
	// 获取日记详情
	GetDiary(context.Context, *GetDiaryRequest) (*GetDiaryResponse, error)
	mustEmbedUnimplementedDiaryServer()
}

// UnimplementedDiaryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiaryServer struct{}

func (UnimplementedDiaryServer) GenerateAvatarDiary(context.Context, *GenerateAvatarDiaryRequest) (*GenerateAvatarDiaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAvatarDiary not implemented")
}
func (UnimplementedDiaryServer) GetAvatarDiaryList(context.Context, *GetAvatarDiaryListRequest) (*GetAvatarDiaryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvatarDiaryList not implemented")
}
func (UnimplementedDiaryServer) CreateUserDiary(context.Context, *CreateUserDiaryRequest) (*CreateUserDiaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserDiary not implemented")
}
func (UnimplementedDiaryServer) GetUserDiaryList(context.Context, *GetUserDiaryListRequest) (*GetUserDiaryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDiaryList not implemented")
}
func (UnimplementedDiaryServer) GetDiaryStats(context.Context, *GetDiaryStatsRequest) (*GetDiaryStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiaryStats not implemented")
}
func (UnimplementedDiaryServer) GetDiary(context.Context, *GetDiaryRequest) (*GetDiaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiary not implemented")
}
func (UnimplementedDiaryServer) mustEmbedUnimplementedDiaryServer() {}
func (UnimplementedDiaryServer) testEmbeddedByValue()               {}

// UnsafeDiaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiaryServer will
// result in compilation errors.
type UnsafeDiaryServer interface {
	mustEmbedUnimplementedDiaryServer()
}

func RegisterDiaryServer(s grpc.ServiceRegistrar, srv DiaryServer) {
	// If the following call pancis, it indicates UnimplementedDiaryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Diary_ServiceDesc, srv)
}

func _Diary_GenerateAvatarDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAvatarDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).GenerateAvatarDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diary_GenerateAvatarDiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).GenerateAvatarDiary(ctx, req.(*GenerateAvatarDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_GetAvatarDiaryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvatarDiaryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).GetAvatarDiaryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diary_GetAvatarDiaryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).GetAvatarDiaryList(ctx, req.(*GetAvatarDiaryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_CreateUserDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).CreateUserDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diary_CreateUserDiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).CreateUserDiary(ctx, req.(*CreateUserDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_GetUserDiaryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDiaryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).GetUserDiaryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diary_GetUserDiaryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).GetUserDiaryList(ctx, req.(*GetUserDiaryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_GetDiaryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiaryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).GetDiaryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diary_GetDiaryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).GetDiaryStats(ctx, req.(*GetDiaryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diary_GetDiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiaryServer).GetDiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Diary_GetDiary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiaryServer).GetDiary(ctx, req.(*GetDiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Diary_ServiceDesc is the grpc.ServiceDesc for Diary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Diary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diary.Diary",
	HandlerType: (*DiaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAvatarDiary",
			Handler:    _Diary_GenerateAvatarDiary_Handler,
		},
		{
			MethodName: "GetAvatarDiaryList",
			Handler:    _Diary_GetAvatarDiaryList_Handler,
		},
		{
			MethodName: "CreateUserDiary",
			Handler:    _Diary_CreateUserDiary_Handler,
		},
		{
			MethodName: "GetUserDiaryList",
			Handler:    _Diary_GetUserDiaryList_Handler,
		},
		{
			MethodName: "GetDiaryStats",
			Handler:    _Diary_GetDiaryStats_Handler,
		},
		{
			MethodName: "GetDiary",
			Handler:    _Diary_GetDiary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diary.proto",
}
