// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: world.proto

package world

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	World_GetMap_FullMethodName             = "/world.World/GetMap"
	World_GetRegion_FullMethodName          = "/world.World/GetRegion"
	World_GetScene_FullMethodName           = "/world.World/GetScene"
	World_ListScenesInRegion_FullMethodName = "/world.World/ListScenesInRegion"
	World_GetScenesForAction_FullMethodName = "/world.World/GetScenesForAction"
	World_ListMaps_FullMethodName           = "/world.World/ListMaps"
	World_ListRegionsInMap_FullMethodName   = "/world.World/ListRegionsInMap"
)

// WorldClient is the client API for World service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// World Service - 世界地图服务
type WorldClient interface {
	// 获取世界地图
	GetMap(ctx context.Context, in *GetMapRequest, opts ...grpc.CallOption) (*GetMapResponse, error)
	// 获取区域详情
	GetRegion(ctx context.Context, in *GetRegionRequest, opts ...grpc.CallOption) (*GetRegionResponse, error)
	// 获取场景详情
	GetScene(ctx context.Context, in *GetSceneRequest, opts ...grpc.CallOption) (*GetSceneResponse, error)
	// 列出区域内的场景
	ListScenesInRegion(ctx context.Context, in *ListScenesInRegionRequest, opts ...grpc.CallOption) (*ListScenesInRegionResponse, error)
	// 根据行为类型推荐场景
	GetScenesForAction(ctx context.Context, in *GetScenesForActionRequest, opts ...grpc.CallOption) (*GetScenesForActionResponse, error)
	// 获取所有地图列表
	ListMaps(ctx context.Context, in *ListMapsRequest, opts ...grpc.CallOption) (*ListMapsResponse, error)
	// 获取地图的所有区域
	ListRegionsInMap(ctx context.Context, in *ListRegionsInMapRequest, opts ...grpc.CallOption) (*ListRegionsInMapResponse, error)
}

type worldClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldClient(cc grpc.ClientConnInterface) WorldClient {
	return &worldClient{cc}
}

func (c *worldClient) GetMap(ctx context.Context, in *GetMapRequest, opts ...grpc.CallOption) (*GetMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMapResponse)
	err := c.cc.Invoke(ctx, World_GetMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldClient) GetRegion(ctx context.Context, in *GetRegionRequest, opts ...grpc.CallOption) (*GetRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegionResponse)
	err := c.cc.Invoke(ctx, World_GetRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldClient) GetScene(ctx context.Context, in *GetSceneRequest, opts ...grpc.CallOption) (*GetSceneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSceneResponse)
	err := c.cc.Invoke(ctx, World_GetScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldClient) ListScenesInRegion(ctx context.Context, in *ListScenesInRegionRequest, opts ...grpc.CallOption) (*ListScenesInRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScenesInRegionResponse)
	err := c.cc.Invoke(ctx, World_ListScenesInRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldClient) GetScenesForAction(ctx context.Context, in *GetScenesForActionRequest, opts ...grpc.CallOption) (*GetScenesForActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScenesForActionResponse)
	err := c.cc.Invoke(ctx, World_GetScenesForAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldClient) ListMaps(ctx context.Context, in *ListMapsRequest, opts ...grpc.CallOption) (*ListMapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMapsResponse)
	err := c.cc.Invoke(ctx, World_ListMaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldClient) ListRegionsInMap(ctx context.Context, in *ListRegionsInMapRequest, opts ...grpc.CallOption) (*ListRegionsInMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegionsInMapResponse)
	err := c.cc.Invoke(ctx, World_ListRegionsInMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorldServer is the server API for World service.
// All implementations must embed UnimplementedWorldServer
// for forward compatibility.
//
// World Service - 世界地图服务
type WorldServer interface {
	// 获取世界地图
	GetMap(context.Context, *GetMapRequest) (*GetMapResponse, error)
	// 获取区域详情
	GetRegion(context.Context, *GetRegionRequest) (*GetRegionResponse, error)
	// 获取场景详情
	GetScene(context.Context, *GetSceneRequest) (*GetSceneResponse, error)
	// 列出区域内的场景
	ListScenesInRegion(context.Context, *ListScenesInRegionRequest) (*ListScenesInRegionResponse, error)
	// 根据行为类型推荐场景
	GetScenesForAction(context.Context, *GetScenesForActionRequest) (*GetScenesForActionResponse, error)
	// 获取所有地图列表
	ListMaps(context.Context, *ListMapsRequest) (*ListMapsResponse, error)
	// 获取地图的所有区域
	ListRegionsInMap(context.Context, *ListRegionsInMapRequest) (*ListRegionsInMapResponse, error)
	mustEmbedUnimplementedWorldServer()
}

// UnimplementedWorldServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorldServer struct{}

func (UnimplementedWorldServer) GetMap(context.Context, *GetMapRequest) (*GetMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMap not implemented")
}
func (UnimplementedWorldServer) GetRegion(context.Context, *GetRegionRequest) (*GetRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegion not implemented")
}
func (UnimplementedWorldServer) GetScene(context.Context, *GetSceneRequest) (*GetSceneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScene not implemented")
}
func (UnimplementedWorldServer) ListScenesInRegion(context.Context, *ListScenesInRegionRequest) (*ListScenesInRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScenesInRegion not implemented")
}
func (UnimplementedWorldServer) GetScenesForAction(context.Context, *GetScenesForActionRequest) (*GetScenesForActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScenesForAction not implemented")
}
func (UnimplementedWorldServer) ListMaps(context.Context, *ListMapsRequest) (*ListMapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMaps not implemented")
}
func (UnimplementedWorldServer) ListRegionsInMap(context.Context, *ListRegionsInMapRequest) (*ListRegionsInMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRegionsInMap not implemented")
}
func (UnimplementedWorldServer) mustEmbedUnimplementedWorldServer() {}
func (UnimplementedWorldServer) testEmbeddedByValue()               {}

// UnsafeWorldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldServer will
// result in compilation errors.
type UnsafeWorldServer interface {
	mustEmbedUnimplementedWorldServer()
}

func RegisterWorldServer(s grpc.ServiceRegistrar, srv WorldServer) {
	// If the following call pancis, it indicates UnimplementedWorldServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&World_ServiceDesc, srv)
}

func _World_GetMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).GetMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: World_GetMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).GetMap(ctx, req.(*GetMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _World_GetRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).GetRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: World_GetRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).GetRegion(ctx, req.(*GetRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _World_GetScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).GetScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: World_GetScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).GetScene(ctx, req.(*GetSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _World_ListScenesInRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenesInRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).ListScenesInRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: World_ListScenesInRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).ListScenesInRegion(ctx, req.(*ListScenesInRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _World_GetScenesForAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScenesForActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).GetScenesForAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: World_GetScenesForAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).GetScenesForAction(ctx, req.(*GetScenesForActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _World_ListMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).ListMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: World_ListMaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).ListMaps(ctx, req.(*ListMapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _World_ListRegionsInMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegionsInMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).ListRegionsInMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: World_ListRegionsInMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).ListRegionsInMap(ctx, req.(*ListRegionsInMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// World_ServiceDesc is the grpc.ServiceDesc for World service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var World_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "world.World",
	HandlerType: (*WorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMap",
			Handler:    _World_GetMap_Handler,
		},
		{
			MethodName: "GetRegion",
			Handler:    _World_GetRegion_Handler,
		},
		{
			MethodName: "GetScene",
			Handler:    _World_GetScene_Handler,
		},
		{
			MethodName: "ListScenesInRegion",
			Handler:    _World_ListScenesInRegion_Handler,
		},
		{
			MethodName: "GetScenesForAction",
			Handler:    _World_GetScenesForAction_Handler,
		},
		{
			MethodName: "ListMaps",
			Handler:    _World_ListMaps_Handler,
		},
		{
			MethodName: "ListRegionsInMap",
			Handler:    _World_ListRegionsInMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "world.proto",
}
