// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: scheduler.proto

package server

import (
	"context"

	"github.com/me2/scheduler/rpc/internal/logic"
	"github.com/me2/scheduler/rpc/internal/svc"
	"github.com/me2/scheduler/rpc/scheduler"
)

type SchedulerServer struct {
	svcCtx *svc.ServiceContext
	scheduler.UnimplementedSchedulerServer
}

func NewSchedulerServer(svcCtx *svc.ServiceContext) *SchedulerServer {
	return &SchedulerServer{
		svcCtx: svcCtx,
	}
}

// 启用分身调度
func (s *SchedulerServer) EnableAvatarSchedule(ctx context.Context, in *scheduler.EnableAvatarScheduleRequest) (*scheduler.EnableAvatarScheduleResponse, error) {
	l := logic.NewEnableAvatarScheduleLogic(ctx, s.svcCtx)
	return l.EnableAvatarSchedule(in)
}

// 暂停分身调度
func (s *SchedulerServer) PauseAvatarSchedule(ctx context.Context, in *scheduler.PauseAvatarScheduleRequest) (*scheduler.PauseAvatarScheduleResponse, error) {
	l := logic.NewPauseAvatarScheduleLogic(ctx, s.svcCtx)
	return l.PauseAvatarSchedule(in)
}

// 恢复分身调度
func (s *SchedulerServer) ResumeAvatarSchedule(ctx context.Context, in *scheduler.ResumeAvatarScheduleRequest) (*scheduler.ResumeAvatarScheduleResponse, error) {
	l := logic.NewResumeAvatarScheduleLogic(ctx, s.svcCtx)
	return l.ResumeAvatarSchedule(in)
}

// 获取分身调度状态
func (s *SchedulerServer) GetAvatarScheduleStatus(ctx context.Context, in *scheduler.GetAvatarScheduleStatusRequest) (*scheduler.GetAvatarScheduleStatusResponse, error) {
	l := logic.NewGetAvatarScheduleStatusLogic(ctx, s.svcCtx)
	return l.GetAvatarScheduleStatus(in)
}

// 手动触发一次调度
func (s *SchedulerServer) TriggerSchedule(ctx context.Context, in *scheduler.TriggerScheduleRequest) (*scheduler.TriggerScheduleResponse, error) {
	l := logic.NewTriggerScheduleLogic(ctx, s.svcCtx)
	return l.TriggerSchedule(in)
}

// 批量获取调度状态
func (s *SchedulerServer) BatchGetScheduleStatus(ctx context.Context, in *scheduler.BatchGetScheduleStatusRequest) (*scheduler.BatchGetScheduleStatusResponse, error) {
	l := logic.NewBatchGetScheduleStatusLogic(ctx, s.svcCtx)
	return l.BatchGetScheduleStatus(in)
}
