// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ActionHistoryRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type ActionHistoryResponse struct {
	Total    int64               `json:"total"`
	Page     int                 `json:"page"`
	PageSize int                 `json:"page_size"`
	List     []ActionLogResponse `json:"list"`
}

type ActionIntentItem struct {
	ActionType string  `json:"action_type"`
	Score      float64 `json:"score"`
	Reason     string  `json:"reason"`
}

type ActionIntentResponse struct {
	Intents        []ActionIntentItem `json:"intents"`
	SelectedAction string             `json:"selected_action"`
}

type ActionLogResponse struct {
	Id            int64   `json:"id"`
	AvatarId      int64   `json:"avatar_id"`
	ActionType    string  `json:"action_type"`
	SceneId       int64   `json:"scene_id"`
	SceneName     string  `json:"scene_name"`
	IntentScore   float64 `json:"intent_score"`
	TriggerReason string  `json:"trigger_reason"`
	EventId       int64   `json:"event_id,omitempty"`
	CreatedAt     int64   `json:"created_at"`
}

type AvatarCompleteRequest struct {
	Key   string `json:"key"`
	Token string `json:"token"`
}

type AvatarCompleteResponse struct {
	AvatarUrl string `json:"avatar_url"`
}

type AvatarResponse struct {
	Id            int64  `json:"id"`
	UserId        int64  `json:"user_id"`
	Name          string `json:"name"`
	AvatarUrl     string `json:"avatar_url"`
	Gender        int64  `json:"gender"`
	BirthDate     string `json:"birth_date"`
	Occupation    string `json:"occupation"`
	MaritalStatus int64  `json:"marital_status"`
	CreatedAt     int64  `json:"created_at"`
}

type AvatarTokenResponse struct {
	Token     string `json:"token"`
	UploadUrl string `json:"upload_url"`
	Key       string `json:"key"`
	Accessid  string `json:"accessid"`
	Policy    string `json:"policy"`
	Signature string `json:"signature"`
	Dir       string `json:"dir"`
}

type AvatarUploadCompleteRequest struct {
	Key   string `json:"key"`
	Token string `json:"token"`
}

type AvatarUploadCompleteResponse struct {
	AvatarUrl string `json:"avatar_url"`
}

type AvatarUploadTokenResponse struct {
	Token     string `json:"token"`
	UploadUrl string `json:"upload_url"`
	Key       string `json:"key"`
	Accessid  string `json:"accessid"`
	Policy    string `json:"policy"`
	Signature string `json:"signature"`
	Dir       string `json:"dir"`
}

type CategoryStat struct {
	Category string  `json:"category"`
	Amount   float64 `json:"amount"`
}

type CreateAvatarRequest struct {
	Name          string `json:"name"`
	AvatarUrl     string `json:"avatar_url,optional"`
	Gender        int64  `json:"gender"`         // 性别 1:男 2:女 3:其他
	BirthDate     string `json:"birth_date"`     // 出生日期 YYYY-MM-DD
	Occupation    string `json:"occupation"`     // 职业
	MaritalStatus int64  `json:"marital_status"` // 婚姻状态 1:单身 2:恋爱中 3:已婚 4:其他
}

type CreateNoteRequest struct {
	AvatarId int64  `json:"avatar_id,optional"`
	RawText  string `json:"raw_text"`
}

type CreateNoteResponse struct {
	Id          int64       `json:"id"`
	Types       []string    `json:"types"`
	AiSummary   string      `json:"ai_summary,optional"`
	EmotionData EmotionData `json:"emotion_data"`
}

type CreateSessionRequest struct {
	AvatarId int64  `json:"avatar_id"`
	Title    string `json:"title,optional"`
}

type CreateSessionResponse struct {
	SessionId int64 `json:"session_id"`
}

type CreateUserDiaryRequest struct {
	Content string `json:"content"`
	Mood    string `json:"mood,optional"`
}

type DailyExpense struct {
	Date   string  `json:"date"`
	Amount float64 `json:"amount"`
}

type DeleteNoteRequest struct {
	Id int64 `path:"id"`
}

type DeleteNoteResponse struct {
	Success bool `json:"success"`
}

type DeleteSessionRequest struct {
	Id int64 `path:"id"`
}

type DeleteSessionResponse struct {
	Success bool `json:"success"`
}

type DiaryListRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type DiaryListResponse struct {
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
	List     []DiaryResponse `json:"list"`
}

type DiaryResponse struct {
	Id           int64  `json:"id"`
	AvatarId     int64  `json:"avatar_id"`
	Type         string `json:"type"`
	Date         string `json:"date"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	Mood         string `json:"mood"`
	ReplyContent string `json:"reply_content,optional"`
	CreatedAt    int64  `json:"created_at"`
}

type DiaryStatsResponse struct {
	TotalCount  int64 `json:"total_count"`
	AvatarCount int64 `json:"avatar_count"`
	UserCount   int64 `json:"user_count"`
}

type EmotionData struct {
	Primary string  `json:"primary"`
	Score   float64 `json:"score"`
}

type EventListRequest struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type EventListResponse struct {
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
	List     []EventResponse `json:"list"`
}

type EventResponse struct {
	Id         int64  `json:"id"`
	AvatarId   int64  `json:"avatar_id"`
	EventType  string `json:"event_type"`
	EventTitle string `json:"event_title"`
	EventText  string `json:"event_text"`
	ImageUrl   string `json:"image_url"`
	SceneId    int64  `json:"scene_id"`
	SceneName  string `json:"scene_name"`
	OccurredAt int64  `json:"occurred_at"`
}

type ExpenseResponse struct {
	Id        int64   `json:"id"`
	NoteId    int64   `json:"note_id"`
	UserId    int64   `json:"user_id"`
	Item      string  `json:"item"`
	Amount    float64 `json:"amount"`
	Category  string  `json:"category"`
	CreatedAt string  `json:"created_at"`
}

type GetAvatarRequest struct {
	Id int64 `path:"id"`
}

type GetDiaryRequest struct {
	Id int64 `path:"id"`
}

type GetEventRequest struct {
	Id int64 `path:"id"`
}

type GetExpenseStatsRequest struct {
	StartDate string `form:"start_date,optional"` // YYYY-MM-DD
	EndDate   string `form:"end_date,optional"`   // YYYY-MM-DD
}

type GetExpenseStatsResponse struct {
	TotalAmount   float64        `json:"total_amount"`
	CategoryStats []CategoryStat `json:"category_stats"`
	DailyExpenses []DailyExpense `json:"daily_expenses"`
}

type GetExpensesRequest struct {
	StartDate string `form:"start_date,optional"` // YYYY-MM-DD
	EndDate   string `form:"end_date,optional"`   // YYYY-MM-DD
	Category  string `form:"category,optional"`
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"page_size,default=20"`
}

type GetExpensesResponse struct {
	Total       int64             `json:"total"`
	TotalAmount float64           `json:"total_amount"`
	List        []ExpenseResponse `json:"list"`
}

type GetMapRequest struct {
	Id int64 `path:"id"`
}

type GetMessagesRequest struct {
	SessionId int64 `path:"session_id"`
	Page      int32 `form:"page,default=1"`
	PageSize  int32 `form:"page_size,default=50"`
}

type GetMessagesResponse struct {
	Messages []Message `json:"messages"`
	Total    int64     `json:"total"`
}

type GetNoteDetailRequest struct {
	Id int64 `path:"id"`
}

type GetNoteDetailResponse struct {
	Note     NoteResponse      `json:"note"`
	Todos    []TodoResponse    `json:"todos"`
	Expenses []ExpenseResponse `json:"expenses"`
}

type GetNotesRequest struct {
	Page     int      `form:"page,default=1"`
	PageSize int      `form:"page_size,default=20"`
	Types    []string `form:"types,optional"`
}

type GetNotesResponse struct {
	Total int64          `json:"total"`
	List  []NoteResponse `json:"list"`
}

type GetRegionRequest struct {
	Id int64 `path:"id"`
}

type GetSceneRequest struct {
	Id int64 `path:"id"`
}

type GetSessionInfoRequest struct {
	Id int64 `path:"id"`
}

type GetSessionInfoResponse struct {
	Session SessionInfo `json:"session"`
}

type GetSessionsRequest struct {
	AvatarId int64 `form:"avatar_id"`
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetSessionsResponse struct {
	Sessions []SessionInfo `json:"sessions"`
	Total    int64         `json:"total"`
}

type GetTodosRequest struct {
	Status   int `form:"status,default=-1"` // -1:全部 0:未完成 1:已完成
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetTodosResponse struct {
	Total int64          `json:"total"`
	List  []TodoResponse `json:"list"`
}

type LoginRequest struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type LoginResponse struct {
	Token    string `json:"token"`
	UserId   int64  `json:"user_id"`
	AvatarId int64  `json:"avatar_id,omitempty"`
}

type MapListRequest struct {
	Page       int  `form:"page,default=1"`
	PageSize   int  `form:"page_size,default=20"`
	OnlyActive bool `form:"only_active,optional"`
}

type MapListResponse struct {
	Total    int64              `json:"total"`
	Page     int                `json:"page"`
	PageSize int                `json:"page_size"`
	List     []WorldMapResponse `json:"list"`
}

type Message struct {
	Id        int64  `json:"id"`
	SessionId int64  `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

type NoteResponse struct {
	Id          int64       `json:"id"`
	UserId      int64       `json:"user_id"`
	AvatarId    int64       `json:"avatar_id,optional"`
	RawText     string      `json:"raw_text"`
	AiSummary   string      `json:"ai_summary,optional"`
	Types       []string    `json:"types"`
	EmotionData EmotionData `json:"emotion_data"`
	CreatedAt   string      `json:"created_at"`
	UpdatedAt   string      `json:"updated_at"`
}

type RegionListRequest struct {
	MapId      int64 `form:"map_id"`
	Page       int   `form:"page,default=1"`
	PageSize   int   `form:"page_size,default=20"`
	OnlyActive bool  `form:"only_active,optional"`
}

type RegionListResponse struct {
	Total    int64                 `json:"total"`
	Page     int                   `json:"page"`
	PageSize int                   `json:"page_size"`
	List     []WorldRegionResponse `json:"list"`
}

type SceneFeaturesResponse struct {
	HasWifi      bool `json:"has_wifi"`
	HasFood      bool `json:"has_food"`
	HasSeating   bool `json:"has_seating"`
	IsIndoor     bool `json:"is_indoor"`
	IsQuiet      bool `json:"is_quiet"`
	ComfortLevel int  `json:"comfort_level"`
	SocialLevel  int  `json:"social_level"`
}

type SceneListRequest struct {
	RegionId   int64    `form:"region_id"`
	Page       int      `form:"page,default=1"`
	PageSize   int      `form:"page_size,default=20"`
	OnlyActive bool     `form:"only_active,optional"`
	Tags       []string `form:"tags,optional"`
}

type SceneListResponse struct {
	Total    int64                `json:"total"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"page_size"`
	List     []WorldSceneResponse `json:"list"`
}

type SceneRecommendationItem struct {
	Scene      WorldSceneResponse `json:"scene"`
	MatchScore float64            `json:"match_score"`
	Reason     string             `json:"reason"`
}

type SceneRecommendationRequest struct {
	ActionType string `form:"action_type"`
	MapId      int64  `form:"map_id,optional"`
	RegionId   int64  `form:"region_id,optional"`
	Limit      int    `form:"limit,default=10"`
}

type SceneRecommendationResponse struct {
	Recommendations []SceneRecommendationItem `json:"recommendations"`
}

type SearchNotesRequest struct {
	Query     string   `form:"query,optional"`
	Types     []string `form:"types,optional"`
	DateRange string   `form:"date_range,optional"` // today, yesterday, last_week, last_month
	Limit     int      `form:"limit,default=20"`
}

type SearchNotesResponse struct {
	List []NoteResponse `json:"list"`
}

type SendCodeRequest struct {
	Phone string `json:"phone"`
}

type SessionInfo struct {
	Id          int64  `json:"id"`
	UserId      int64  `json:"user_id"`
	AvatarId    int64  `json:"avatar_id"`
	Title       string `json:"title"`
	LastMessage string `json:"last_message"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type SubscriptionResponse struct {
	UserId           int64 `json:"user_id"`
	SubscriptionTier int32 `json:"subscription_tier"`
	ExpiresAt        int64 `json:"expires_at,omitempty"`
	AutoRenew        bool  `json:"auto_renew"`
}

type TodoResponse struct {
	Id          int64  `json:"id"`
	NoteId      int64  `json:"note_id"`
	UserId      int64  `json:"user_id"`
	Title       string `json:"title"`
	DueDate     string `json:"due_date,optional"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"created_at"`
	CompletedAt string `json:"completed_at,optional"`
}

type UpdateAvatarRequest struct {
	Id            int64  `path:"id"`
	Name          string `json:"name,optional"`
	AvatarUrl     string `json:"avatar_url,optional"`
	Gender        int64  `json:"gender,optional"`
	BirthDate     string `json:"birth_date,optional"`
	Occupation    string `json:"occupation,optional"`
	MaritalStatus int64  `json:"marital_status,optional"`
}

type UpdateNoteRequest struct {
	Id      int64  `path:"id"`
	RawText string `json:"raw_text"`
}

type UpdateNoteResponse struct {
	Success   bool     `json:"success"`
	Types     []string `json:"types"`
	AiSummary string   `json:"ai_summary,optional"`
}

type UpdateSubscriptionRequest struct {
	UserId           int64 `json:"user_id"`
	SubscriptionTier int32 `json:"subscription_tier"`
	ExpiresAt        int64 `json:"expires_at,optional"`
}

type UpdateTodoStatusRequest struct {
	Id     int64 `path:"id"`
	Status int   `json:"status"` // 0:未完成 1:已完成
}

type UpdateTodoStatusResponse struct {
	Success bool `json:"success"`
}

type UpdateUserRequest struct {
	Nickname  string `json:"nickname,optional"`
	AvatarUrl string `json:"avatar_url,optional"`
}

type UpdateUserStatusRequest struct {
	UserId int64 `json:"user_id"`
	Status int32 `json:"status"`
}

type UserInfoResponse struct {
	UserId           int64  `json:"user_id"`
	Phone            string `json:"phone"`
	Nickname         string `json:"nickname"`
	AvatarUrl        string `json:"avatar_url"`
	SubscriptionTier int32  `json:"subscription_tier"`
	Status           int32  `json:"status"`
	CreatedAt        int64  `json:"created_at"`
}

type WorldMapResponse struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CoverImage  string `json:"cover_image"`
	IsActive    bool   `json:"is_active"`
	CreatedAt   int64  `json:"created_at"`
}

type WorldRegionResponse struct {
	Id          int64    `json:"id"`
	MapId       int64    `json:"map_id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	CoverImage  string   `json:"cover_image"`
	Atmosphere  string   `json:"atmosphere"`
	Tags        []string `json:"tags"`
	IsActive    bool     `json:"is_active"`
	CreatedAt   int64    `json:"created_at"`
}

type WorldSceneResponse struct {
	Id              int64                 `json:"id"`
	RegionId        int64                 `json:"region_id"`
	Name            string                `json:"name"`
	Description     string                `json:"description"`
	CoverImage      string                `json:"cover_image"`
	Atmosphere      string                `json:"atmosphere"`
	Tags            []string              `json:"tags"`
	SuitableActions []string              `json:"suitable_actions"`
	Capacity        int                   `json:"capacity"`
	IsActive        bool                  `json:"is_active"`
	Features        SceneFeaturesResponse `json:"features"`
	CreatedAt       int64                 `json:"created_at"`
}
