// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: oss.proto

package server

import (
	"context"

	"github.com/me2/oss/rpc/internal/logic"
	"github.com/me2/oss/rpc/internal/svc"
	"github.com/me2/oss/rpc/oss"
)

type OssServer struct {
	svcCtx *svc.ServiceContext
	oss.UnimplementedOssServer
}

func NewOssServer(svcCtx *svc.ServiceContext) *OssServer {
	return &OssServer{
		svcCtx: svcCtx,
	}
}

// 获取上传 Token（包含 policy 和 signature）
func (s *OssServer) GetUploadToken(ctx context.Context, in *oss.GetUploadTokenRequest) (*oss.GetUploadTokenResponse, error) {
	l := logic.NewGetUploadTokenLogic(ctx, s.svcCtx)
	return l.GetUploadToken(in)
}

// 完成上传（验证并返回文件 URL）
func (s *OssServer) CompleteUpload(ctx context.Context, in *oss.CompleteUploadRequest) (*oss.CompleteUploadResponse, error) {
	l := logic.NewCompleteUploadLogic(ctx, s.svcCtx)
	return l.CompleteUpload(in)
}
