// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: oss.proto

package oss_client

import (
	"context"

	"github.com/me2/oss/rpc/oss"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CompleteUploadRequest  = oss.CompleteUploadRequest
	CompleteUploadResponse = oss.CompleteUploadResponse
	GetUploadTokenRequest  = oss.GetUploadTokenRequest
	GetUploadTokenResponse = oss.GetUploadTokenResponse

	Oss interface {
		// 获取上传 Token（包含 policy 和 signature）
		GetUploadToken(ctx context.Context, in *GetUploadTokenRequest, opts ...grpc.CallOption) (*GetUploadTokenResponse, error)
		// 完成上传（验证并返回文件 URL）
		CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
	}

	defaultOss struct {
		cli zrpc.Client
	}
)

func NewOss(cli zrpc.Client) Oss {
	return &defaultOss{
		cli: cli,
	}
}

// 获取上传 Token（包含 policy 和 signature）
func (m *defaultOss) GetUploadToken(ctx context.Context, in *GetUploadTokenRequest, opts ...grpc.CallOption) (*GetUploadTokenResponse, error) {
	client := oss.NewOssClient(m.cli.Conn())
	return client.GetUploadToken(ctx, in, opts...)
}

// 完成上传（验证并返回文件 URL）
func (m *defaultOss) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	client := oss.NewOssClient(m.cli.Conn())
	return client.CompleteUpload(ctx, in, opts...)
}
