// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: dialogue.proto

package dialogue_client

import (
	"context"

	"github.com/me2/dialogue/rpc/dialogue"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatStreamRequest      = dialogue.ChatStreamRequest
	ChatStreamResponse     = dialogue.ChatStreamResponse
	CreateSessionRequest   = dialogue.CreateSessionRequest
	CreateSessionResponse  = dialogue.CreateSessionResponse
	DeleteSessionRequest   = dialogue.DeleteSessionRequest
	DeleteSessionResponse  = dialogue.DeleteSessionResponse
	GetMessagesRequest     = dialogue.GetMessagesRequest
	GetMessagesResponse    = dialogue.GetMessagesResponse
	GetSessionInfoRequest  = dialogue.GetSessionInfoRequest
	GetSessionInfoResponse = dialogue.GetSessionInfoResponse
	GetSessionsRequest     = dialogue.GetSessionsRequest
	GetSessionsResponse    = dialogue.GetSessionsResponse
	Message                = dialogue.Message
	SessionInfo            = dialogue.SessionInfo

	Dialogue interface {
		// 创建会话
		CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
		// 获取会话列表
		GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error)
		// 获取会话详情
		GetSessionInfo(ctx context.Context, in *GetSessionInfoRequest, opts ...grpc.CallOption) (*GetSessionInfoResponse, error)
		// 获取对话历史
		GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
		// 流式对话
		ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (dialogue.Dialogue_ChatStreamClient, error)
		// 删除会话
		DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	}

	defaultDialogue struct {
		cli zrpc.Client
	}
)

func NewDialogue(cli zrpc.Client) Dialogue {
	return &defaultDialogue{
		cli: cli,
	}
}

// 创建会话
func (m *defaultDialogue) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	client := dialogue.NewDialogueClient(m.cli.Conn())
	return client.CreateSession(ctx, in, opts...)
}

// 获取会话列表
func (m *defaultDialogue) GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error) {
	client := dialogue.NewDialogueClient(m.cli.Conn())
	return client.GetSessions(ctx, in, opts...)
}

// 获取会话详情
func (m *defaultDialogue) GetSessionInfo(ctx context.Context, in *GetSessionInfoRequest, opts ...grpc.CallOption) (*GetSessionInfoResponse, error) {
	client := dialogue.NewDialogueClient(m.cli.Conn())
	return client.GetSessionInfo(ctx, in, opts...)
}

// 获取对话历史
func (m *defaultDialogue) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	client := dialogue.NewDialogueClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

// 流式对话
func (m *defaultDialogue) ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (dialogue.Dialogue_ChatStreamClient, error) {
	client := dialogue.NewDialogueClient(m.cli.Conn())
	return client.ChatStream(ctx, in, opts...)
}

// 删除会话
func (m *defaultDialogue) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	client := dialogue.NewDialogueClient(m.cli.Conn())
	return client.DeleteSession(ctx, in, opts...)
}
