// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: diary.proto

package server

import (
	"context"

	"github.com/me2/diary/rpc/diary"
	"github.com/me2/diary/rpc/internal/logic"
	"github.com/me2/diary/rpc/internal/svc"
)

type DiaryServer struct {
	svcCtx *svc.ServiceContext
	diary.UnimplementedDiaryServer
}

func NewDiaryServer(svcCtx *svc.ServiceContext) *DiaryServer {
	return &DiaryServer{
		svcCtx: svcCtx,
	}
}

// 生成分身日记（由 Scheduler 调用）
func (s *DiaryServer) GenerateAvatarDiary(ctx context.Context, in *diary.GenerateAvatarDiaryRequest) (*diary.GenerateAvatarDiaryResponse, error) {
	l := logic.NewGenerateAvatarDiaryLogic(ctx, s.svcCtx)
	return l.GenerateAvatarDiary(in)
}

// 获取分身日记列表
func (s *DiaryServer) GetAvatarDiaryList(ctx context.Context, in *diary.GetAvatarDiaryListRequest) (*diary.GetAvatarDiaryListResponse, error) {
	l := logic.NewGetAvatarDiaryListLogic(ctx, s.svcCtx)
	return l.GetAvatarDiaryList(in)
}

// 创建用户日记
func (s *DiaryServer) CreateUserDiary(ctx context.Context, in *diary.CreateUserDiaryRequest) (*diary.CreateUserDiaryResponse, error) {
	l := logic.NewCreateUserDiaryLogic(ctx, s.svcCtx)
	return l.CreateUserDiary(in)
}

// 获取用户日记列表
func (s *DiaryServer) GetUserDiaryList(ctx context.Context, in *diary.GetUserDiaryListRequest) (*diary.GetUserDiaryListResponse, error) {
	l := logic.NewGetUserDiaryListLogic(ctx, s.svcCtx)
	return l.GetUserDiaryList(in)
}

// 获取日记统计
func (s *DiaryServer) GetDiaryStats(ctx context.Context, in *diary.GetDiaryStatsRequest) (*diary.GetDiaryStatsResponse, error) {
	l := logic.NewGetDiaryStatsLogic(ctx, s.svcCtx)
	return l.GetDiaryStats(in)
}
