// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package server

import (
	"context"

	"github.com/me2/user/rpc/internal/logic"
	"github.com/me2/user/rpc/internal/svc"
	"github.com/me2/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 发送验证码
func (s *UserServer) SendVerifyCode(ctx context.Context, in *user.SendVerifyCodeRequest) (*user.SendVerifyCodeResponse, error) {
	l := logic.NewSendVerifyCodeLogic(ctx, s.svcCtx)
	return l.SendVerifyCode(in)
}

// 登录或注册（手机号+验证码）
func (s *UserServer) LoginOrRegister(ctx context.Context, in *user.LoginOrRegisterRequest) (*user.LoginOrRegisterResponse, error) {
	l := logic.NewLoginOrRegisterLogic(ctx, s.svcCtx)
	return l.LoginOrRegister(in)
}

// 获取用户信息
func (s *UserServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoRequest) (*user.GetUserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// 更新订阅状态
func (s *UserServer) UpdateSubscription(ctx context.Context, in *user.UpdateSubscriptionRequest) (*user.UpdateSubscriptionResponse, error) {
	l := logic.NewUpdateSubscriptionLogic(ctx, s.svcCtx)
	return l.UpdateSubscription(in)
}

// 获取订阅信息
func (s *UserServer) GetSubscription(ctx context.Context, in *user.GetSubscriptionRequest) (*user.GetSubscriptionResponse, error) {
	l := logic.NewGetSubscriptionLogic(ctx, s.svcCtx)
	return l.GetSubscription(in)
}

// 更新用户状态
func (s *UserServer) UpdateUserStatus(ctx context.Context, in *user.UpdateUserStatusRequest) (*user.UpdateUserStatusResponse, error) {
	l := logic.NewUpdateUserStatusLogic(ctx, s.svcCtx)
	return l.UpdateUserStatus(in)
}

// 更新用户信息（昵称、头像）
func (s *UserServer) UpdateUserInfo(ctx context.Context, in *user.UpdateUserInfoRequest) (*user.UpdateUserInfoResponse, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

// 获取头像上传凭证
func (s *UserServer) GetAvatarUploadToken(ctx context.Context, in *user.GetAvatarUploadTokenRequest) (*user.GetAvatarUploadTokenResponse, error) {
	l := logic.NewGetAvatarUploadTokenLogic(ctx, s.svcCtx)
	return l.GetAvatarUploadToken(in)
}

// 完成头像上传
func (s *UserServer) CompleteAvatarUpload(ctx context.Context, in *user.CompleteAvatarUploadRequest) (*user.CompleteAvatarUploadResponse, error) {
	l := logic.NewCompleteAvatarUploadLogic(ctx, s.svcCtx)
	return l.CompleteAvatarUpload(in)
}
