// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	diariesFieldNames          = builder.RawFieldNames(&Diaries{})
	diariesRows                = strings.Join(diariesFieldNames, ",")
	diariesRowsExpectAutoSet   = strings.Join(stringx.Remove(diariesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	diariesRowsWithPlaceHolder = strings.Join(stringx.Remove(diariesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	diariesModel interface {
		Insert(ctx context.Context, data *Diaries) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Diaries, error)
		FindOneByAvatarIdTypeDate(ctx context.Context, avatarId int64, tp string, date time.Time) (*Diaries, error)
		Update(ctx context.Context, data *Diaries) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDiariesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Diaries struct {
		Id           int64          `db:"id"`
		AvatarId     int64          `db:"avatar_id"`     // 分身ID
		Type         string         `db:"type"`          // 日记类型
		Date         time.Time      `db:"date"`          // 日记日期
		Title        string         `db:"title"`         // 标题
		Content      string         `db:"content"`       // 内容
		Mood         string         `db:"mood"`          // 心情
		Tags         string         `db:"tags"`          // 标签（JSON数组）
		ReplyContent sql.NullString `db:"reply_content"` // 分身回应（仅user类型）
		EmotionScore int64          `db:"emotion_score"` // 情绪分数 -100到100（仅user类型）
		IsImportant  int64          `db:"is_important"`  // 是否重要
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
	}
)

func newDiariesModel(conn sqlx.SqlConn) *defaultDiariesModel {
	return &defaultDiariesModel{
		conn:  conn,
		table: "`diaries`",
	}
}

func (m *defaultDiariesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDiariesModel) FindOne(ctx context.Context, id int64) (*Diaries, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", diariesRows, m.table)
	var resp Diaries
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDiariesModel) FindOneByAvatarIdTypeDate(ctx context.Context, avatarId int64, tp string, date time.Time) (*Diaries, error) {
	var resp Diaries
	query := fmt.Sprintf("select %s from %s where `avatar_id` = ? and `type` = ? and `date` = ? limit 1", diariesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, avatarId, tp, date)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDiariesModel) Insert(ctx context.Context, data *Diaries) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, diariesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AvatarId, data.Type, data.Date, data.Title, data.Content, data.Mood, data.Tags, data.ReplyContent, data.EmotionScore, data.IsImportant)
	return ret, err
}

func (m *defaultDiariesModel) Update(ctx context.Context, newData *Diaries) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, diariesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AvatarId, newData.Type, newData.Date, newData.Title, newData.Content, newData.Mood, newData.Tags, newData.ReplyContent, newData.EmotionScore, newData.IsImportant, newData.Id)
	return err
}

func (m *defaultDiariesModel) tableName() string {
	return m.table
}
