// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: oss.proto

package ossclient

import (
	"context"

	"github.com/me2/oss/rpc/oss"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteFileRequest      = oss.DeleteFileRequest
	DeleteFileResponse     = oss.DeleteFileResponse
	GetDownloadUrlRequest  = oss.GetDownloadUrlRequest
	GetDownloadUrlResponse = oss.GetDownloadUrlResponse
	GetUploadUrlRequest    = oss.GetUploadUrlRequest
	GetUploadUrlResponse   = oss.GetUploadUrlResponse

	Oss interface {
		// 获取上传签名 URL
		GetUploadUrl(ctx context.Context, in *GetUploadUrlRequest, opts ...grpc.CallOption) (*GetUploadUrlResponse, error)
		// 获取下载 URL
		GetDownloadUrl(ctx context.Context, in *GetDownloadUrlRequest, opts ...grpc.CallOption) (*GetDownloadUrlResponse, error)
		// 删除文件
		DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	}

	defaultOss struct {
		cli zrpc.Client
	}
)

func NewOss(cli zrpc.Client) Oss {
	return &defaultOss{
		cli: cli,
	}
}

// 获取上传签名 URL
func (m *defaultOss) GetUploadUrl(ctx context.Context, in *GetUploadUrlRequest, opts ...grpc.CallOption) (*GetUploadUrlResponse, error) {
	client := oss.NewOssClient(m.cli.Conn())
	return client.GetUploadUrl(ctx, in, opts...)
}

// 获取下载 URL
func (m *defaultOss) GetDownloadUrl(ctx context.Context, in *GetDownloadUrlRequest, opts ...grpc.CallOption) (*GetDownloadUrlResponse, error) {
	client := oss.NewOssClient(m.cli.Conn())
	return client.GetDownloadUrl(ctx, in, opts...)
}

// 删除文件
func (m *defaultOss) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	client := oss.NewOssClient(m.cli.Conn())
	return client.DeleteFile(ctx, in, opts...)
}
