// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: ai.proto

package ai_client

import (
	"context"

	"github.com/me2/ai/rpc/ai"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionIntentRequest    = ai.ActionIntentRequest
	ActionIntentResponse   = ai.ActionIntentResponse
	AnalyzeEmotionRequest  = ai.AnalyzeEmotionRequest
	AnalyzeEmotionResponse = ai.AnalyzeEmotionResponse
	AvatarState            = ai.AvatarState
	ChatRequest            = ai.ChatRequest
	ChatResponse           = ai.ChatResponse
	ChatStreamResponse     = ai.ChatStreamResponse
	EmbeddingRequest       = ai.EmbeddingRequest
	EmbeddingResponse      = ai.EmbeddingResponse
	GenerateRequest        = ai.GenerateRequest
	GenerateResponse       = ai.GenerateResponse
	GetPromptsRequest      = ai.GetPromptsRequest
	GetPromptsResponse     = ai.GetPromptsResponse
	GetStatsRequest        = ai.GetStatsRequest
	GetStatsResponse       = ai.GetStatsResponse
	HealthCheckRequest     = ai.HealthCheckRequest
	HealthCheckResponse    = ai.HealthCheckResponse
	ModelConfig            = ai.ModelConfig
	PersonalityVector      = ai.PersonalityVector
	PromptTemplate         = ai.PromptTemplate
	TimeContext            = ai.TimeContext

	Ai interface {
		// 对话生成（非流式）
		Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
		// 对话生成（流式）
		ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (ai.Ai_ChatStreamClient, error)
		// 文本生成（事件、日记等）
		Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
		// 情绪分析
		AnalyzeEmotion(ctx context.Context, in *AnalyzeEmotionRequest, opts ...grpc.CallOption) (*AnalyzeEmotionResponse, error)
		// 文本向量化
		Embedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
		// 行动意图计算（供 Action Service 调用）
		CalculateActionIntent(ctx context.Context, in *ActionIntentRequest, opts ...grpc.CallOption) (*ActionIntentResponse, error)
		// 获取 Prompt 模板列表
		GetPrompts(ctx context.Context, in *GetPromptsRequest, opts ...grpc.CallOption) (*GetPromptsResponse, error)
		// 获取使用统计
		GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
		// 健康检查
		HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	}

	defaultAi struct {
		cli zrpc.Client
	}
)

func NewAi(cli zrpc.Client) Ai {
	return &defaultAi{
		cli: cli,
	}
}

// 对话生成（非流式）
func (m *defaultAi) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

// 对话生成（流式）
func (m *defaultAi) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (ai.Ai_ChatStreamClient, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.ChatStream(ctx, in, opts...)
}

// 文本生成（事件、日记等）
func (m *defaultAi) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.Generate(ctx, in, opts...)
}

// 情绪分析
func (m *defaultAi) AnalyzeEmotion(ctx context.Context, in *AnalyzeEmotionRequest, opts ...grpc.CallOption) (*AnalyzeEmotionResponse, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.AnalyzeEmotion(ctx, in, opts...)
}

// 文本向量化
func (m *defaultAi) Embedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.Embedding(ctx, in, opts...)
}

// 行动意图计算（供 Action Service 调用）
func (m *defaultAi) CalculateActionIntent(ctx context.Context, in *ActionIntentRequest, opts ...grpc.CallOption) (*ActionIntentResponse, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.CalculateActionIntent(ctx, in, opts...)
}

// 获取 Prompt 模板列表
func (m *defaultAi) GetPrompts(ctx context.Context, in *GetPromptsRequest, opts ...grpc.CallOption) (*GetPromptsResponse, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.GetPrompts(ctx, in, opts...)
}

// 获取使用统计
func (m *defaultAi) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.GetStats(ctx, in, opts...)
}

// 健康检查
func (m *defaultAi) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	client := ai.NewAiClient(m.cli.Conn())
	return client.HealthCheck(ctx, in, opts...)
}
