// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: note.proto

package server

import (
	"context"

	"github.com/me2/note/rpc/internal/logic"
	"github.com/me2/note/rpc/internal/svc"
	"github.com/me2/note/rpc/note"
)

type NoteServiceServer struct {
	svcCtx *svc.ServiceContext
	note.UnimplementedNoteServiceServer
}

func NewNoteServiceServer(svcCtx *svc.ServiceContext) *NoteServiceServer {
	return &NoteServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建笔记
func (s *NoteServiceServer) CreateNote(ctx context.Context, in *note.CreateNoteRequest) (*note.CreateNoteResponse, error) {
	l := logic.NewCreateNoteLogic(ctx, s.svcCtx)
	return l.CreateNote(in)
}

// 获取笔记列表
func (s *NoteServiceServer) GetNotes(ctx context.Context, in *note.GetNotesRequest) (*note.GetNotesResponse, error) {
	l := logic.NewGetNotesLogic(ctx, s.svcCtx)
	return l.GetNotes(in)
}

// 获取笔记详情
func (s *NoteServiceServer) GetNoteDetail(ctx context.Context, in *note.GetNoteDetailRequest) (*note.GetNoteDetailResponse, error) {
	l := logic.NewGetNoteDetailLogic(ctx, s.svcCtx)
	return l.GetNoteDetail(in)
}

// 更新笔记
func (s *NoteServiceServer) UpdateNote(ctx context.Context, in *note.UpdateNoteRequest) (*note.UpdateNoteResponse, error) {
	l := logic.NewUpdateNoteLogic(ctx, s.svcCtx)
	return l.UpdateNote(in)
}

// 删除笔记
func (s *NoteServiceServer) DeleteNote(ctx context.Context, in *note.DeleteNoteRequest) (*note.DeleteNoteResponse, error) {
	l := logic.NewDeleteNoteLogic(ctx, s.svcCtx)
	return l.DeleteNote(in)
}

// 搜索笔记（用于对话集成）
func (s *NoteServiceServer) SearchNotes(ctx context.Context, in *note.SearchNotesRequest) (*note.SearchNotesResponse, error) {
	l := logic.NewSearchNotesLogic(ctx, s.svcCtx)
	return l.SearchNotes(in)
}

// 获取 TODO 列表
func (s *NoteServiceServer) GetTodos(ctx context.Context, in *note.GetTodosRequest) (*note.GetTodosResponse, error) {
	l := logic.NewGetTodosLogic(ctx, s.svcCtx)
	return l.GetTodos(in)
}

// 更新 TODO 状态
func (s *NoteServiceServer) UpdateTodoStatus(ctx context.Context, in *note.UpdateTodoStatusRequest) (*note.UpdateTodoStatusResponse, error) {
	l := logic.NewUpdateTodoStatusLogic(ctx, s.svcCtx)
	return l.UpdateTodoStatus(in)
}

// 获取记账列表
func (s *NoteServiceServer) GetExpenses(ctx context.Context, in *note.GetExpensesRequest) (*note.GetExpensesResponse, error) {
	l := logic.NewGetExpensesLogic(ctx, s.svcCtx)
	return l.GetExpenses(in)
}

// 获取记账统计
func (s *NoteServiceServer) GetExpenseStats(ctx context.Context, in *note.GetExpenseStatsRequest) (*note.GetExpenseStatsResponse, error) {
	l := logic.NewGetExpenseStatsLogic(ctx, s.svcCtx)
	return l.GetExpenseStats(in)
}
