// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: sms.proto

package sms_client

import (
	"context"

	"github.com/me2/sms/rpc/sms"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendCodeRequest    = sms.SendCodeRequest
	SendCodeResponse   = sms.SendCodeResponse
	VerifyCodeRequest  = sms.VerifyCodeRequest
	VerifyCodeResponse = sms.VerifyCodeResponse

	Sms interface {
		// 发送验证码
		SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error)
		// 验证验证码
		VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error)
	}

	defaultSms struct {
		cli zrpc.Client
	}
)

func NewSms(cli zrpc.Client) Sms {
	return &defaultSms{
		cli: cli,
	}
}

// 发送验证码
func (m *defaultSms) SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}

// 验证验证码
func (m *defaultSms) VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.VerifyCode(ctx, in, opts...)
}
