// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	action "github.com/me2/gateway/api/internal/handler/action"
	avatar "github.com/me2/gateway/api/internal/handler/avatar"
	diary "github.com/me2/gateway/api/internal/handler/diary"
	event "github.com/me2/gateway/api/internal/handler/event"
	user "github.com/me2/gateway/api/internal/handler/user"
	world "github.com/me2/gateway/api/internal/handler/world"
	"github.com/me2/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 获取分身行动历史
					Method:  http.MethodGet,
					Path:    "/history",
					Handler: action.GetHistoryHandler(serverCtx),
				},
				{
					// 计算分身行动意图
					Method:  http.MethodGet,
					Path:    "/intent",
					Handler: action.CalculateIntentHandler(serverCtx),
				},
				{
					// 获取最近一次行动
					Method:  http.MethodGet,
					Path:    "/last",
					Handler: action.GetLastActionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/action"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 获取分身详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: avatar.GetAvatarHandler(serverCtx),
				},
				{
					// 更新分身资料
					Method:  http.MethodPatch,
					Path:    "/:id",
					Handler: avatar.UpdateAvatarHandler(serverCtx),
				},
				{
					// 更新分身性格
					Method:  http.MethodPut,
					Path:    "/:id/personality",
					Handler: avatar.UpdatePersonalityHandler(serverCtx),
				},
				{
					// 完成分身头像上传
					Method:  http.MethodPost,
					Path:    "/avatar-complete",
					Handler: avatar.CompleteAvatarUploadHandler(serverCtx),
				},
				{
					// 获取分身头像上传凭证
					Method:  http.MethodGet,
					Path:    "/avatar-token",
					Handler: avatar.GetAvatarUploadTokenHandler(serverCtx),
				},
				{
					// 创建分身
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: avatar.CreateAvatarHandler(serverCtx),
				},
				{
					// 获取我的分身
					Method:  http.MethodGet,
					Path:    "/my",
					Handler: avatar.GetMyAvatarHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/avatar"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 获取日记详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: diary.GetDiaryHandler(serverCtx),
				},
				{
					// 获取分身日记列表
					Method:  http.MethodGet,
					Path:    "/avatar",
					Handler: diary.GetAvatarDiariesHandler(serverCtx),
				},
				{
					// 获取日记统计
					Method:  http.MethodGet,
					Path:    "/stats",
					Handler: diary.GetDiaryStatsHandler(serverCtx),
				},
				{
					// 获取用户日记列表
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: diary.GetUserDiariesHandler(serverCtx),
				},
				{
					// 创建用户日记
					Method:  http.MethodPost,
					Path:    "/user",
					Handler: diary.CreateUserDiaryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/diary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 获取事件详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: event.GetEventHandler(serverCtx),
				},
				{
					// 获取分身事件时间线
					Method:  http.MethodGet,
					Path:    "/timeline",
					Handler: event.GetEventTimelineHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/events"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 发送验证码
				Method:  http.MethodPost,
				Path:    "/send-code",
				Handler: user.SendCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 完成头像上传
					Method:  http.MethodPost,
					Path:    "/avatar-complete",
					Handler: user.CompleteAvatarHandler(serverCtx),
				},
				{
					// 获取头像上传凭证
					Method:  http.MethodGet,
					Path:    "/avatar-token",
					Handler: user.GetAvatarTokenHandler(serverCtx),
				},
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					// 更新用户状态
					Method:  http.MethodPut,
					Path:    "/status",
					Handler: user.UpdateUserStatusHandler(serverCtx),
				},
				{
					// 获取订阅信息
					Method:  http.MethodGet,
					Path:    "/subscription",
					Handler: user.GetSubscriptionHandler(serverCtx),
				},
				{
					// 更新订阅
					Method:  http.MethodPut,
					Path:    "/subscription",
					Handler: user.UpdateSubscriptionHandler(serverCtx),
				},
				{
					// 更新用户信息
					Method:  http.MethodPut,
					Path:    "/update",
					Handler: user.UpdateUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 获取世界地图列表
					Method:  http.MethodGet,
					Path:    "/maps",
					Handler: world.ListMapsHandler(serverCtx),
				},
				{
					// 获取世界地图详情
					Method:  http.MethodGet,
					Path:    "/maps/:id",
					Handler: world.GetMapHandler(serverCtx),
				},
				{
					// 根据行为类型推荐场景
					Method:  http.MethodGet,
					Path:    "/recommend",
					Handler: world.RecommendScenesHandler(serverCtx),
				},
				{
					// 获取地图的区域列表
					Method:  http.MethodGet,
					Path:    "/regions",
					Handler: world.ListRegionsHandler(serverCtx),
				},
				{
					// 获取区域详情
					Method:  http.MethodGet,
					Path:    "/regions/:id",
					Handler: world.GetRegionHandler(serverCtx),
				},
				{
					// 获取区域内的场景列表
					Method:  http.MethodGet,
					Path:    "/scenes",
					Handler: world.ListScenesHandler(serverCtx),
				},
				{
					// 获取场景详情
					Method:  http.MethodGet,
					Path:    "/scenes/:id",
					Handler: world.GetSceneHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/world"),
	)
}
