// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: event.proto

package event_client

import (
	"context"

	"github.com/me2/event/rpc/event"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EventInfo                = event.EventInfo
	GenerateEventRequest     = event.GenerateEventRequest
	GenerateEventResponse    = event.GenerateEventResponse
	GetEventDetailRequest    = event.GetEventDetailRequest
	GetEventDetailResponse   = event.GetEventDetailResponse
	GetEventTimelineRequest  = event.GetEventTimelineRequest
	GetEventTimelineResponse = event.GetEventTimelineResponse
	GetTemplatesRequest      = event.GetTemplatesRequest
	GetTemplatesResponse     = event.GetTemplatesResponse
	TemplateInfo             = event.TemplateInfo

	Event interface {
		// 生成事件
		GenerateEvent(ctx context.Context, in *GenerateEventRequest, opts ...grpc.CallOption) (*GenerateEventResponse, error)
		// 获取事件时间线
		GetEventTimeline(ctx context.Context, in *GetEventTimelineRequest, opts ...grpc.CallOption) (*GetEventTimelineResponse, error)
		// 获取事件详情
		GetEventDetail(ctx context.Context, in *GetEventDetailRequest, opts ...grpc.CallOption) (*GetEventDetailResponse, error)
		// 获取模板列表（后续可用于管理后台）
		GetTemplates(ctx context.Context, in *GetTemplatesRequest, opts ...grpc.CallOption) (*GetTemplatesResponse, error)
	}

	defaultEvent struct {
		cli zrpc.Client
	}
)

func NewEvent(cli zrpc.Client) Event {
	return &defaultEvent{
		cli: cli,
	}
}

// 生成事件
func (m *defaultEvent) GenerateEvent(ctx context.Context, in *GenerateEventRequest, opts ...grpc.CallOption) (*GenerateEventResponse, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GenerateEvent(ctx, in, opts...)
}

// 获取事件时间线
func (m *defaultEvent) GetEventTimeline(ctx context.Context, in *GetEventTimelineRequest, opts ...grpc.CallOption) (*GetEventTimelineResponse, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetEventTimeline(ctx, in, opts...)
}

// 获取事件详情
func (m *defaultEvent) GetEventDetail(ctx context.Context, in *GetEventDetailRequest, opts ...grpc.CallOption) (*GetEventDetailResponse, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetEventDetail(ctx, in, opts...)
}

// 获取模板列表（后续可用于管理后台）
func (m *defaultEvent) GetTemplates(ctx context.Context, in *GetTemplatesRequest, opts ...grpc.CallOption) (*GetTemplatesResponse, error) {
	client := event.NewEventClient(m.cli.Conn())
	return client.GetTemplates(ctx, in, opts...)
}
