// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: dialogue.proto

package server

import (
	"context"

	"github.com/me2/dialogue/rpc/dialogue"
	"github.com/me2/dialogue/rpc/internal/logic"
	"github.com/me2/dialogue/rpc/internal/svc"
)

type DialogueServer struct {
	svcCtx *svc.ServiceContext
	dialogue.UnimplementedDialogueServer
}

func NewDialogueServer(svcCtx *svc.ServiceContext) *DialogueServer {
	return &DialogueServer{
		svcCtx: svcCtx,
	}
}

// 创建会话
func (s *DialogueServer) CreateSession(ctx context.Context, in *dialogue.CreateSessionRequest) (*dialogue.CreateSessionResponse, error) {
	l := logic.NewCreateSessionLogic(ctx, s.svcCtx)
	return l.CreateSession(in)
}

// 获取会话列表
func (s *DialogueServer) GetSessions(ctx context.Context, in *dialogue.GetSessionsRequest) (*dialogue.GetSessionsResponse, error) {
	l := logic.NewGetSessionsLogic(ctx, s.svcCtx)
	return l.GetSessions(in)
}

// 获取会话详情
func (s *DialogueServer) GetSessionInfo(ctx context.Context, in *dialogue.GetSessionInfoRequest) (*dialogue.GetSessionInfoResponse, error) {
	l := logic.NewGetSessionInfoLogic(ctx, s.svcCtx)
	return l.GetSessionInfo(in)
}

// 获取对话历史
func (s *DialogueServer) GetMessages(ctx context.Context, in *dialogue.GetMessagesRequest) (*dialogue.GetMessagesResponse, error) {
	l := logic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}

// 流式对话
func (s *DialogueServer) ChatStream(in *dialogue.ChatStreamRequest, stream dialogue.Dialogue_ChatStreamServer) error {
	l := logic.NewChatStreamLogic(stream.Context(), s.svcCtx)
	return l.ChatStream(in, stream)
}

// 删除会话
func (s *DialogueServer) DeleteSession(ctx context.Context, in *dialogue.DeleteSessionRequest) (*dialogue.DeleteSessionResponse, error) {
	l := logic.NewDeleteSessionLogic(ctx, s.svcCtx)
	return l.DeleteSession(in)
}
