// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: action.proto

package server

import (
	"context"

	"github.com/me2/action/rpc/action"
	"github.com/me2/action/rpc/internal/logic"
	"github.com/me2/action/rpc/internal/svc"
)

type ActionServer struct {
	svcCtx *svc.ServiceContext
	action.UnimplementedActionServer
}

func NewActionServer(svcCtx *svc.ServiceContext) *ActionServer {
	return &ActionServer{
		svcCtx: svcCtx,
	}
}

// 调度行动 - 由定时任务调用，触发分身行动
func (s *ActionServer) ScheduleAction(ctx context.Context, in *action.ScheduleActionRequest) (*action.ScheduleActionResponse, error) {
	l := logic.NewScheduleActionLogic(ctx, s.svcCtx)
	return l.ScheduleAction(in)
}

// 计算行动意图 - 计算 6 种行为的得分
func (s *ActionServer) CalculateActionIntent(ctx context.Context, in *action.CalculateActionIntentRequest) (*action.CalculateActionIntentResponse, error) {
	l := logic.NewCalculateActionIntentLogic(ctx, s.svcCtx)
	return l.CalculateActionIntent(in)
}

// 获取行动历史
func (s *ActionServer) GetActionHistory(ctx context.Context, in *action.GetActionHistoryRequest) (*action.GetActionHistoryResponse, error) {
	l := logic.NewGetActionHistoryLogic(ctx, s.svcCtx)
	return l.GetActionHistory(in)
}

// 获取最近一次行动
func (s *ActionServer) GetLastAction(ctx context.Context, in *action.GetLastActionRequest) (*action.GetLastActionResponse, error) {
	l := logic.NewGetLastActionLogic(ctx, s.svcCtx)
	return l.GetLastAction(in)
}
